// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
require({cache:{"dojo/debounce":function(){define([],function(){return function(p,w){var l;return function(){l&&clearTimeout(l);var d=this,k=arguments;l=setTimeout(function(){p.apply(d,k)},w)}}})},"esri/numberUtils":function(){define(["dojo/has","dojo/number","dojo/i18n!dojo/cldr/nls/number","./kernel"],function(p,w,l,d){var k=function(d,f){return d-f},x={_reNumber:/^-?(\d+)(\.(\d+))?$/i,getDigits:function(d){var f=String(d),h=f.match(x._reNumber);d={integer:0,fractional:0};h&&h[1]?(d.integer=h[1].split("").length,
d.fractional=h[3]?h[3].split("").length:0):-1<f.toLowerCase().indexOf("e")&&(h=f.split("e"),f=h[0],h=h[1],f&&h&&(f=Number(f),h=Number(h),(d=0<h)||(h=Math.abs(h)),f=x.getDigits(f),d?(f.integer+=h,f.fractional=h>f.fractional?0:f.fractional-h):(f.fractional+=h,f.integer=h>f.integer?1:f.integer-h),d=f));return d},getFixedNumbers:function(d,f){var h,l;h=Number(d.toFixed(f));h<d?l=h+1/Math.pow(10,f):(l=h,h-=1/Math.pow(10,f));h=Number(h.toFixed(f));l=Number(l.toFixed(f));return[h,l]},getPctChange:function(d,
f,h,l){var k={prev:null,next:null},q;null!=h&&(q=d-h,h=f-h-q,k.prev=Math.floor(Math.abs(100*h/q)));null!=l&&(q=l-d,h=l-f-q,k.next=Math.floor(Math.abs(100*h/q)));return k},round:function(d,f){var h=d.slice(0),l,p,q,v,b,n,w,C,A,r=!f||null==f.tolerance?2:f.tolerance,y=f&&f.indexes,O=!f||null==f.strictBounds?!1:f.strictBounds;if(y)y.sort(k);else{y=[];for(n=0;n<h.length;n++)y.push(n)}for(n=0;n<y.length;n++)if(A=y[n],l=h[A],p=0===A?null:h[A-1],q=A===h.length-1?null:h[A+1],v=x.getDigits(l),v=v.fractional){w=
0;for(C=!1;w<=v&&!C;)b=x.getFixedNumbers(l,w),b=O&&0===n?b[1]:b[0],C=x.hasMinimalChange(l,b,p,q,r),w++;C&&(h[A]=b)}return h},hasMinimalChange:function(d,l,h,k,p){d=x.getPctChange(d,l,h,k);l=null==d.prev||d.prev<=p;h=null==d.next||d.next<=p;return l&&h||d.prev+d.next<=2*p},_reAllZeros:RegExp("\\"+l.decimal+"0+$","g"),_reSomeZeros:RegExp("(\\d)0*$","g"),format:function(d,l){l=l||{places:20,round:-1};var h=w.format(d,l);h&&(h=h.replace(x._reSomeZeros,"$1").replace(x._reAllZeros,""));return h}};p("extend-esri")&&
(d.numberUtils=x);return x})},"esri/renderers/utils":function(){define("dojo/_base/lang dojo/_base/array dojo/has dojo/date/locale ../kernel ../numberUtils ../Color dojo/i18n!../nls/jsapi dojo/i18n!dojo/cldr/nls/gregorian".split(" "),function(p,w,l,d,k,x,B,f,h){function Q(b){return b&&w.map(b,function(b){return new B(b)})}function K(b,r,d){var h="";0===r?h=v.lt+" ":r===d&&(h=v.gt+" ");return h+b}var q={},v={lte:"\x3c\x3d",gte:"\x3e\x3d",lt:"\x3c",gt:"\x3e",pct:"%"},b={millisecond:0,second:1,minute:2,
hour:3,day:4,month:5,year:6},n={millisecond:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},second:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"medium"}},minute:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},hour:{dateOptions:{formatLength:"long"},timeOptions:{formatLength:"short"}},day:{selector:"date",dateOptions:{formatLength:"long"}},month:{selector:"date",dateOptions:{formatLength:"long"}},year:{selector:"date",dateOptions:{selector:"year"}}},
R={formatLength:"short",fullYear:!0},C={formatLength:"short"};p.mixin(q,{timelineDateFormatOptions:{selector:"date",dateOptions:{formatLength:"short",fullYear:!0}},formatDate:function(b,r){var l,f=[];null!=b&&!(b instanceof Date)&&(b=new Date(b));r=r||{};r=p.mixin({},r);var k=r.selector?r.selector.toLowerCase():null;l=!k||-1<k.indexOf("time");k=!k||-1<k.indexOf("date");l&&(r.timeOptions=r.timeOptions||C,r.timeOptions&&(r.timeOptions=p.mixin({},r.timeOptions),r.timeOptions.selector=r.timeOptions.selector||
"time",f.push(r.timeOptions)));k&&(r.dateOptions=r.dateOptions||R,r.dateOptions&&(r.dateOptions=p.mixin({},r.dateOptions),r.dateOptions.selector=r.dateOptions.selector||"date",f.push(r.dateOptions)));f&&f.length?(f=w.map(f,function(r){return d.format(b,r)}),l=1==f.length?f[0]:h["dateTimeFormat-medium"].replace(/\'/g,"").replace(/\{(\d+)\}/g,function(b,r){return f[r]})):l=d.format(b);return l},createColorStops:function(b){var r=b.values,d=b.colors,h=b.labelIndexes,l=b.isDate,f=b.dateFormatOptions;
b=[];return b=w.map(r,function(b,A){var k=null;if(!h||-1<w.indexOf(h,A)){var n;(n=l?q.formatDate(b,f):x.format(b))&&(k=K(n,A,r.length-1))}return{value:b,color:d[A],label:k}})},updateColorStops:function(b){var r=b.stops,d=b.changes,h=b.isDate,l=b.dateFormatOptions,f=[],k,n=w.map(r,function(b){return b.value});w.forEach(d,function(b){f.push(b.index);n[b.index]=b.value});k=x.round(n,{indexes:f});w.forEach(r,function(b,d){b.value=n[d];if(null!=b.label){var A,f=null;(A=h?q.formatDate(k[d],l):x.format(k[d]))&&
(f=K(A,d,r.length-1));b.label=f}})},createClassBreakLabel:function(b){var d=b.minValue,h=b.maxValue,l=b.isFirstBreak?"":v.gt+" ";b="percent-of-total"===b.normalizationType?v.pct:"";d=null==d?"":x.format(d);h=null==h?"":x.format(h);return l+d+b+" "+f.smartMapping.minToMax+" "+h+b},setLabelsForClassBreaks:function(b){var d=b.classBreaks,h=b.classificationMethod,l=b.normalizationType,f=[];d&&d.length&&("standard-deviation"===h?console.log("setLabelsForClassBreaks: cannot set labels for class breaks generated using 'standard-deviation' method."):
b.round?(f.push(d[0].minValue),w.forEach(d,function(b){f.push(b.maxValue)}),f=x.round(f),w.forEach(d,function(b,d){b.label=q.createClassBreakLabel({minValue:0===d?f[0]:f[d],maxValue:f[d+1],isFirstBreak:0===d,normalizationType:l})})):w.forEach(d,function(b,d){b.label=q.createClassBreakLabel({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===d,normalizationType:l})}))},updateClassBreak:function(b){var d=b.classBreaks,h=b.normalizationType,l=b.change,f=l.index,l=l.value,k=-1,n=-1,p=d.length;"standard-deviation"===
b.classificationMethod?console.log("updateClassBreak: cannot update labels for class breaks generated using 'standard-deviation' method."):(0===f?k=f:f===p?n=f-1:(n=f-1,k=f),-1<k&&k<p&&(b=d[k],b.minValue=l,b.label=q.createClassBreakLabel({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===k,normalizationType:h})),-1<n&&n<p&&(b=d[n],b.maxValue=l,b.label=q.createClassBreakLabel({minValue:b.minValue,maxValue:b.maxValue,isFirstBreak:0===n,normalizationType:h})))},calculateDateFormatInterval:function(d){var h,
l,f=d.length,k,n,p,v,q,x,B=Infinity,C;d=w.map(d,function(b){return new Date(b)});for(h=0;h<f-1;h++){k=d[h];p=[];q=Infinity;x="";for(l=h+1;l<f;l++)n=d[l],n=k.getFullYear()!==n.getFullYear()&&"year"||k.getMonth()!==n.getMonth()&&"month"||k.getDate()!==n.getDate()&&"day"||k.getHours()!==n.getHours()&&"hour"||k.getMinutes()!==n.getMinutes()&&"minute"||k.getSeconds()!==n.getSeconds()&&"second"||"millisecond",v=b[n],v<q&&(q=v,x=n),p.push(n);q<B&&(B=q,C=x)}return C},createUniqueValueLabel:function(b){var d=
b.value,h=b.fieldInfo,l=b.domain;b=b.dateFormatInterval;var f=String(d);(l=l&&l.codedValues?l.getName(d):null)?f=l:"number"===typeof d&&(f=h&&"esriFieldTypeDate"===h.type?q.formatDate(d,b&&n[b]):x.format(d));return f},cloneColorInfo:function(b){var d;b&&(d=p.mixin({},b),d.colors=Q(d.colors),d.stops=d.stops&&w.map(d.stops,function(b){b=p.mixin({},b);b.color&&(b.color=new B(b.color));return b}),d.legendOptions&&(d.legendOptions=p.mixin({},d.legendOptions)));return d},cloneOpacityInfo:function(b){var d;
if(b){d=p.mixin({},b);if(b=d.opacityValues)d.opacityValues=b.slice(0);if(b=d.stops)d.stops=w.map(b,function(b){return p.mixin({},b)});if(b=d.legendOptions)d.legendOptions=p.mixin({},b)}return d},cloneSizeInfo:function(b){var d;if(b){d=p.mixin({},b);d.stops&&(d.stops=w.map(d.stops,function(b){return p.mixin({},b)}));if((b=d.minSize)&&"object"===typeof b)d.minSize=q.cloneSizeInfo(b);if((b=d.maxSize)&&"object"===typeof b)d.maxSize=q.cloneSizeInfo(b);if(b=d.legendOptions)if(d.legendOptions=p.mixin({},
b),b=b.customValues)d.legendOptions.customValues=b.slice(0)}return d}});l("extend-esri")&&p.setObject("renderer.utils",q,k);return q})},"*noref":1}});
define("esri/dijit/Legend","dojo/_base/kernel dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/_base/json dojo/_base/Color dojo/debounce dojo/has dojo/sniff dojo/DeferredList dojo/json dojo/dom dojo/dom-construct dojo/dom-style dojo/dom-class dijit/_Widget dojox/gfx dojox/gfx/matrix dojox/html/entities ../kernel ../config ../request ../lang ../numberUtils ../renderers/utils ../renderers/SimpleRenderer ../renderers/UniqueValueRenderer ../renderers/ClassBreaksRenderer ../renderers/ScaleDependentRenderer ../renderers/DotDensityRenderer ../renderers/TemporalRenderer ../renderers/VectorFieldRenderer ../renderers/HeatmapRenderer ../symbols/PictureFillSymbol ../symbols/SimpleLineSymbol ../symbols/jsonUtils ./_EventedWidget dojo/i18n!../nls/jsapi".split(" "),function(p,
w,l,d,k,x,B,f,h,Q,K,q,v,b,n,R,C,A,r,y,O,S,T,H,F,L,I,M,J,W,X,Y,P,Z,$,aa,N,ba,U){var G=w([ba,C],{declaredClass:"esri.dijit.Legend",widgetsInTemplate:!1,layers:null,alignRight:!1,hoverLabelShowing:!1,dotDensitySwatchSize:26,dotCoverage:75,gradientHeight:30,transparencyRampColor:new B([64,64,64]),defaultText:"Aa",sizeRampLightColor:new B([255,255,255]),sizeRampDarkColor:new B([128,128,128]),layerConnects:[],gradientWidth:34,colorRampBorder:"1px solid",_specialChars:{lt:"\x3c",gt:"\x3e"},_ieTimer:100,
_isRightToLeft:!1,_align:null,_legendAlign:null,constructor:function(a,c){l.mixin(this,U.widgets.legend);this._i18n=U.widgets.legend;a=a||{};a.map?c?(this.map=a.map,this.layerInfos=a.layerInfos,this._respectCurrentMapScale=!1===a.respectCurrentMapScale?!1:!0,this._respectVisibility=!1===a.respectVisibility?!1:!0,this.arrangement=a.arrangement===G.ALIGN_RIGHT?G.ALIGN_RIGHT:G.ALIGN_LEFT,this.arrangement===G.ALIGN_RIGHT&&(this.alignRight=!0),this.autoUpdate=!1===a.autoUpdate?!1:!0,this._surfaceItems=
[],this.hideLayersInLegend={},this.refresh=f(this.refresh,0)):console.error("esri.dijit.Legend: must specify a container for the legend"):console.error("esri.dijit.Legend: unable to find the 'map' property in parameters")},postMixInProperties:function(){this.inherited(arguments);var a=["ar","he"],c,g;for(c=0;c<a.length;c+=1)g=a[c],p.locale&&-1!==p.locale.indexOf(g)&&(-1!==p.locale.indexOf("-")?-1!==p.locale.indexOf(g+"-")&&(this._isRightToLeft=!0):this._isRightToLeft=!0);this._isRightToLeft?(this._align=
this.alignRight?"left":"right",this._legendAlign=this.alignRight?"esriLegendLeft":"esriLegendRight"):(this._align=this.alignRight?"right":"left",this._legendAlign=this.alignRight?"esriLegendRight":"esriLegendLeft")},startup:function(){this.inherited(arguments);this._initialize();9>h("ie")&&(this._repaintItems=l.hitch(this,this._repaintItems),setTimeout(this._repaintItems,this._ieTimer))},destroy:function(){this._deactivate();this._removeHoverHandlers();this.inherited(arguments)},refresh:function(a){if(this.domNode){a?
(this.layerInfos=a,this.layers=[],d.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=a.hideLayers,this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this)):this.useAllMapLayers&&(this.layers=
this.layerInfos=null);for(a=this.domNode.children.length-1;0<=a;a--)b.destroy(this.domNode.children[a]);this._removeHoverHandlers();this.startup()}},_legendUrl:"http://utility.arcgis.com/sharing/tools/legend",_initialize:function(){this.layerInfos&&(this.layers=[],d.forEach(this.layerInfos,function(a){this._isSupportedLayerType(a.layer)&&(a.title&&(a.layer._titleForLegend=a.title),a.layer._hideDefaultSymbol=!1===a.defaultSymbol?!0:!1,a.hideLayers?(this.hideLayersInLegend[a.layer.id]=a.hideLayers,
this._addSubLayersToHide(a)):this.hideLayersInLegend[a.layer.id]=[],a.hoverLabel&&(a.layer._hoverLabel=a.hoverLabel),a.hoverLabels&&(a.layer._hoverLabels=a.hoverLabels),this.layers.push(a.layer))},this));this.useAllMapLayers=!1;if(!this.layers){this.useAllMapLayers=!0;this.layers=[];var a=[],c=[];d.forEach(this.map.layerIds,function(g){g=this.map.getLayer(g);var b;this._isSupportedLayerType(g)&&(g.arcgisProps&&g.arcgisProps.title&&(g._titleForLegend=g.arcgisProps.title),this.layers.push(g));"esri.layers.KMLLayer"==
g.declaredClass&&(b=g.getLayers(),d.forEach(b,function(c){a.push(c.id)},this));"esri.layers.GeoRSSLayer"==g.declaredClass&&(b=g.getFeatureLayers(),d.forEach(b,function(a){c.push(a.id)},this))},this);d.forEach(this.map.graphicsLayerIds,function(g){var b=this.map.getLayer(g);-1==d.indexOf(a,g)&&-1==d.indexOf(c,g)&&(this._isSupportedLayerType(b)&&b._params&&b._params.drawMode)&&(b.arcgisProps&&b.arcgisProps.title&&(b._titleForLegend=b.arcgisProps.title),this.layers.push(b))},this)}this._createLegend()},
_activate:function(){this._deactivate();this.autoUpdate&&(this._respectCurrentMapScale&&(this._ozeConnect=k.connect(this.map,"onZoomEnd",this,"_refreshLayers")),this.useAllMapLayers&&(this._olaConnect=k.connect(this.map,"onLayerAdd",this,"_updateAllMapLayers"),this._olrConnect=k.connect(this.map,"onLayerRemove",this,"_updateAllMapLayers"),this._olroConnect=k.connect(this.map,"onLayersReordered",this,"_updateAllMapLayers")),d.forEach(this.layers,function(a){var c={};c.ovcConnect=k.connect(a,"onVisibilityChange",
this,"_refreshLayers");c.oocConnect=k.connect(a,"onOpacityChange",this,"_refreshLayers");c.oscConnect=k.connect(a,"onScaleRangeChange",this,"_refreshLayers");"esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass&&a.supportsDynamicLayers&&(c.odcConnect=k.connect(a,"_onDynamicLayersChange",l.hitch(this,"_updateDynamicLayers",a)));"esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&(c.oirConnect=k.connect(a,"onRenderingChange",l.partial(this._updateImageServiceLayers,this,a)));"esri.layers.ArcGISImageServiceVectorLayer"===
a.declaredClass&&(c.oivrConnect=k.connect(a,"onRendererChange",l.hitch(this,"_refreshLayers")));this.layerConnects[a.id]=c},this))},_deactivate:function(){this._ozeConnect&&k.disconnect(this._ozeConnect);this._olaConnect&&k.disconnect(this._olaConnect);this._olroConnect&&k.disconnect(this._olroConnect);this._olrConnect&&k.disconnect(this._olrConnect);d.forEach(this.layers,function(a){a=this.layerConnects[a.id]||{};a.ovcConnect&&k.disconnect(a.ovcConnect);a.oocConnect&&k.disconnect(a.oocConnect);a.oscConnect&&
k.disconnect(a.oscConnect);a.odcConnect&&k.disconnect(a.odcConnect);a.oirConnect&&k.disconnect(a.oirConnect);a.oivrConnect&&k.disconnect(a.oivrConnect)},this);this.layerConnects=[]},_updateDynamicLayers:function(a){delete a.legendResponse;this._refreshLayers()},_updateImageServiceLayers:function(a,c){delete c.legendResponse;a._refreshLayers()},_refreshLayers:function(){this.refresh()},_updateAllMapLayers:function(){this.layers=[];d.forEach(this.map.layerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&
this.layers.push(a)},this);d.forEach(this.map.graphicsLayerIds,function(a){a=this.map.getLayer(a);this._isSupportedLayerType(a)&&(a._params&&a._params.drawMode)&&this.layers.push(a)},this);this.refresh()},_createLegend:function(){var a=!1,c=!1;n.set(this.domNode,"position","relative");b.create("div",{id:this.id+"_msg",className:"esriLegendMsg",innerHTML:this.NLS_creatingLegend+"..."},this.domNode);var g=[];d.forEach(this.layers,function(e){if("esri.layers.KMLLayer"==e.declaredClass||"esri.layers.GeoRSSLayer"==
e.declaredClass){var t;e.loaded?("esri.layers.KMLLayer"==e.declaredClass?t=e.getLayers():"esri.layers.GeoRSSLayer"==e.declaredClass&&(t=e.getFeatureLayers(),this.hideLayersInLegend[e.id]&&(t=d.filter(t,function(a){return-1==d.indexOf(this.hideLayersInLegend[e.id],a.id)},this))),d.forEach(t,function(a){"esri.layers.FeatureLayer"==a.declaredClass&&e._titleForLegend&&(a._titleForLegend=e._titleForLegend+" - ","esriGeometryPoint"==a.geometryType?a._titleForLegend+=this.NLS_points:"esriGeometryPolyline"==
a.geometryType?a._titleForLegend+=this.NLS_lines:"esriGeometryPolygon"==a.geometryType&&(a._titleForLegend+=this.NLS_polygons),g.push(a))},this)):k.connect(e,"onLoad",l.hitch(this,function(){this.refresh(this.layerInfos)}))}else if("esri.layers.WMSLayer"===e.declaredClass)if(e.loaded){if((!this._respectVisibility||this._respectVisibility&&e.visible)&&0<e.layerInfos.length&&d.some(e.layerInfos,function(a){return a.legendURL})){var z=!1;d.forEach(e.layerInfos,function(c){if(c.legendURL&&-1<d.indexOf(e.visibleLayers,
c.name)){z||(b.create("div",{innerHTML:"\x3cspan class\x3d'esriLegendServiceLabel'\x3e"+(e._titleForLegend||e.name||e.id)+"\x3c/span\x3e"},this.domNode),z=!0);var g;c=c.legendURL;if(e.customParameters||e.customLayerParameters){var t=l.clone(e.customParameters||{});l.mixin(t,e.customLayerParameters||{});for(g in t)c+=(-1===c.indexOf("?")?"?":"\x26")+g+"\x3d"+t[g]}b.create("div",{innerHTML:"\x3cimg src\x3d'"+c+"'/\x3e"},this.domNode);a=!0}},this)}}else k.connect(e,"onLoad",l.hitch(this,function(){this.refresh(this.layerInfos)}));
else"esri.layers.WFSLayer"===e.declaredClass&&!e.renderer?(t=b.create("div",{id:this.id+"_"+e.id,"class":"esriLegendService"}),b.create("span",{innerHTML:this._getServiceTitle(e),"class":"esriLegendServiceLabel"},b.create("td",{align:this._align},b.create("tr",{},b.create("tbody",{},b.create("table",{width:"95%"},t))))),b.place(t,this.id,"first"),tableNode=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},t),tableBody=b.create("tbody",{},tableNode),"esriGeometryComplex"===
e.geometryType?(this._buildRow_Renderer(e,e._pointSymbol,null,this.NLS_points,null,tableBody),this._buildRow_Renderer(e,e._lineSymbol,null,this.NLS_lines,null,tableBody),this._buildRow_Renderer(e,e._polygonSymbol,null,this.NLS_areas,null,tableBody)):"esriGeometryPoint"===e.geometryType?this._buildRow_Renderer(e,e._pointSymbol,null,"",null,tableBody):"esriGeometryPolyline"===e.geometryType?this._buildRow_Renderer(e,e._lineSymbol,null,"",null,tableBody):"esriGeometryPolygon"===e.geometryType&&this._buildRow_Renderer(e,
e._polygonSymbol,null,"",null,tableBody),c=!0):g.push(e)},this);var t=[];d.forEach(g,function(a){if(a.loaded){if((!this._respectVisibility||this._respectVisibility&&a.visible)&&(a.layerInfos||a.renderer||"esri.layers.ArcGISImageServiceLayer"==a.declaredClass)){var c=b.create("div",{id:this.id+"_"+a.id,style:{display:"none"},"class":"esriLegendService"});b.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},b.create("td",{align:this._align},b.create("tr",{},b.create("tbody",
{},b.create("table",{width:"95%"},c)))));b.place(c,this.id,"first");a.legendResponse||a.renderer?this._createLegendForLayer(a):t.push(this._legendRequest(a))}}else var g=k.connect(a,"onLoad",this,function(a){k.disconnect(g);g=null;this.refresh()})},this);0===t.length&&!a&&!c?(v.byId(this.id+"_msg").innerHTML=this.NLS_noLegend,this._activate()):(new K(t)).addCallback(l.hitch(this,function(g){!a&&!c?v.byId(this.id+"_msg").innerHTML=this.NLS_noLegend:v.byId(this.id+"_msg").innerHTML="";this._activate()}))},
_createLegendForLayer:function(a){if(a.legendResponse||a.renderer){var c=!1;if(a.legendResponse){var g=a.dynamicLayerInfos||a.layerInfos;g&&g.length?d.forEach(g,function(g,e){if(!this.hideLayersInLegend[a.id]||-1===d.indexOf(this.hideLayersInLegend[a.id],g.id)){var b=this._buildLegendItems(a,g,e);c=c||b}},this):"esri.layers.ArcGISImageServiceLayer"==a.declaredClass&&(c=this._buildLegendItems(a,{id:0,name:null,title:a.name,subLayerIds:null,parentLayerId:-1},0))}else a.renderer&&(g=a.url?a.url.substring(a.url.lastIndexOf("/")+
1,a.url.length):"fc_"+a.id,c=this._buildLegendItems(a,{id:g,name:null,subLayerIds:null,parentLayerId:-1},0));c&&(n.set(v.byId(this.id+"_"+a.id),"display","block"),n.set(v.byId(this.id+"_msg"),"display","none"))}},_legendRequest:function(a){if(a.loaded)return 10.01<=a.version?this._legendRequestServer(a):this._legendRequestTools(a);k.connect(a,"onLoad",l.hitch(this,"_legendRequest"))},_legendRequestServer:function(a){var c=a.url,g=c.indexOf("?"),c=-1<g?c.substring(0,g)+"/legend"+c.substring(g):c+"/legend";
(g=a._getToken())&&(c+="?token\x3d"+g);var b=l.hitch(this,"_processLegendResponse"),e={f:"json"};a._params.dynamicLayers&&(e.dynamicLayers=q.stringify(this._createDynamicLayers(a)),"[{}]"===e.dynamicLayers&&(e.dynamicLayers="[]"));a._params.bandIds&&(e.bandIds=a._params.bandIds);a._params.renderingRule?e.renderingRule=a._params.renderingRule:a.rasterFunctionInfos&&0<a.rasterFunctionInfos.length&&d.forEach(a.rasterFunctionInfos,function(a){a&&(a.name&&"none"===a.name.toLowerCase())&&(e.renderingRule=
q.stringify({rasterFunction:a.name}))});return T({url:c,content:e,callbackParamName:"callback",load:function(c,g){b(a,c,g)},error:S.defaults.io.errorHandler})},_legendRequestTools:function(a){var c=a.url.toLowerCase().indexOf("/rest/"),c=a.url.substring(0,c)+a.url.substring(c+5,a.url.length),c=this._legendUrl+"?soapUrl\x3d"+window.escape(c);if(!h("ie")||8<h("ie"))c+="\x26returnbytes\x3dtrue";var g=l.hitch(this,"_processLegendResponse");return T({url:c,content:{f:"json"},callbackParamName:"callback",
load:function(c,e){g(a,c,e)},error:S.defaults.io.errorHandler})},_processLegendResponse:function(a,c){c&&c.layers?(a.legendResponse=c,v.byId(this.id+"_"+a.id)&&b.empty(v.byId(this.id+"_"+a.id)),b.create("span",{innerHTML:this._getServiceTitle(a),"class":"esriLegendServiceLabel"},b.create("td",{align:this._align},b.create("tr",{},b.create("tbody",{},b.create("table",{width:"95%"},v.byId(this.id+"_"+a.id)))))),this._createLegendForLayer(a)):console.log("Legend could not get generated for "+a.url+": "+
x.toJson(c))},_buildLegendItems:function(a,c,g){var t=!1,e=v.byId(this.id+"_"+a.id),s=c.parentLayerId;if(c.subLayerIds)a=b.create("div",{id:this.id+"_"+a.id+"_"+c.id+"_group",style:{display:"none"},"class":-1==s?0<g?"esriLegendGroupLayer":"":this._legendAlign},-1==s?e:v.byId(this.id+"_"+a.id+"_"+s+"_group")),b.create("td",{innerHTML:y.encode(c.name),align:this._align},b.create("tr",{},b.create("tbody",{},b.create("table",{width:"95%","class":"esriLegendLayerLabel"},a))));else{if(this._respectVisibility&&
a.visibleLayers)if(g=a.dynamicLayerInfos||a.layerInfos)if(a._params&&a._params.layers){if(-1===d.indexOf(a.visibleLayers,c.id))return t}else{if(g=this._getReallyVisibleLayers(g,a.visibleLayers),-1===d.indexOf(g,c.id))return t}else if(-1===d.indexOf(a.visibleLayers,c.id))return t;e=b.create("div",{id:this.id+"_"+a.id+"_"+c.id,style:{display:"none"},"class":-1<s?this._legendAlign:""},-1==s?e:v.byId(this.id+"_"+a.id+"_"+s+"_group"));b.create("td",{innerHTML:y.encode(c.name)||"",align:this._align},b.create("tr",
{},b.create("tbody",{},b.create("table",{width:"95%","class":"esriLegendLayerLabel"},e))));a.legendResponse?t=t||this._buildLegendItems_Tools(a,c,e):a.renderer&&(t=t||this._buildLegendItems_Renderer(a,c,e))}return t},_getReallyVisibleLayers:function(a,c){if(!a||!c||!c.length)return[];var g=[],b=[],e;for(e=0;e<a.length;e++)if(a[e].subLayerIds){if(-1===d.indexOf(c,a[e].id)||-1<d.indexOf(b,a[e].id))b=b.concat(a[e].subLayerIds)}else-1<d.indexOf(c,a[e].id)&&-1===d.indexOf(b,a[e].id)&&g.push(a[e].id);return g},
_buildLegendItems_Tools:function(a,c,g){var t=c.parentLayerId,e=this.map.getScale(),s=!1,z=function(a,c){var g,e;for(g=0;g<a.length;g++)if(c.dynamicLayerInfos)for(e=0;e<c.dynamicLayerInfos[e].length;e++){if(c.dynamicLayerInfos[e].mapLayerId==a[g].layerId)return a[g]}else if(c.id==a[g].layerId)return a[g];return{}};if(!this._respectCurrentMapScale||this._respectCurrentMapScale&&this._isLayerInScale(a,c,e)){var V=!0;if(this._respectCurrentMapScale&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||
"esri.layers.ArcGISMapServiceLayer"===a.declaredClass)){var h=this._getEffectiveScale(a,c);if(h.minScale&&h.minScale<e||h.maxScale&&h.maxScale>e)V=!1}if(V){var e=z(a.legendResponse.layers,c),l=e.legendType,m=e.layerType,f=e.legend;if(f){"esri.layers.ArcGISImageServiceLayer"!==a.declaredClass&&this._sanitizeLegendResponse(a,e,c);g=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);var k=b.create("tbody",{},g);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(g,
a,c);d.forEach(f,function(g){if(!(10.1<=a.version&&!g.values&&1<f.length&&(a._hideDefaultSymbol||"\x3call other values\x3e"===g.label||!g.label&&!("esri.layers.ArcGISImageServiceLayer"===a.declaredClass&&10.3<=a.version||"Raster Layer"===m))))if(g.url&&0===g.url.indexOf("http")||g.imageData&&0<g.imageData.length)s=!0,this._buildRow_Tools(g,k,a,c.id,l)},this)}}}s&&(n.set(v.byId(this.id+"_"+a.id+"_"+c.id),"display","block"),-1<t&&(n.set(v.byId(this.id+"_"+a.id+"_"+t+"_group"),"display","block"),this._findParentGroup(a.id,
a,t)));return s},_sanitizeLegendResponse:function(a,c,g){var b=c.legend;if(10.1<=a.version&&1<b.length&&!c._sanitized){a=l.getObject("layerDefinition.drawingInfo.renderer",!1,g);var e,s;a||(a=l.getObject("drawingInfo.renderer",!1,g));d.some(b,function(a){if(a.values)return!0})&&d.some(b,function(a,c){a.values||(s=c,e=a);return!!e});a?"uniqueValue"===a.type?e&&(b.splice(s,1),b.push(e)):"classBreaks"===a.type&&(e&&b.splice(s,1),b.reverse(),e&&b.push(e)):e&&(b.splice(s,1),b.push(e));c._sanitized=!0}},
_buildRow_Tools:function(a,c,g,t,e){var d=b.create("tr",{},c),z;this.alignRight?(c=b.create("td",{align:this._isRightToLeft?"left":"right"},d),z=b.create("td",{align:this._isRightToLeft?"left":"right",width:35},d)):(z=b.create("td",{width:35,align:"center"},d),c=b.create("td",{},d));d=a.url;(!h("ie")||9<=h("ie")||9>h("ie")&&"esri.layers.ArcGISImageServiceLayer"===g.declaredClass)&&a.imageData&&0<a.imageData.length?d="data:image/png;base64,"+a.imageData:0!==a.url.indexOf("http")&&(d=g.url+"/"+t+"/images/"+
a.url,(t=g._getToken())&&(d+="?token\x3d"+t));t=b.create("img",{src:d,border:0,style:"opacity:"+g.opacity},z);a=b.create("td",{innerHTML:y.encode(a.label),align:this._align},b.create("tr",{},b.create("tbody",{},b.create("table",{width:"95%",dir:"ltr"},c))));e&&("Stretched"===e&&10.3<=g.version&&"esri.layers.ArcGISImageServiceLayer"===g.declaredClass)&&(a.style.verticalAlign="top",a.style.lineHeight="1",t.style.marginBottom="-1px",t.style.display="block",c.style.verticalAlign="top");9>h("ie")&&(t.style.filter=
"alpha(opacity\x3d"+100*g.opacity+")")},_getVariable:function(a,c,g){var b;a&&(b=(a=a.getVisualVariablesForType(c,g))&&a[0]);return b},_getVariables:function(a,c,g){a=[this._getVariable(a,"colorInfo",!1),this._getVariable(a,"opacityInfo",!1),this._getVariable(a,"sizeInfo",!1)];return c?d.filter(a,function(a){return!(!a||!(a.field===c&&a.normalizationField==g))}):a},_getFieldAlias:function(a,c){var g=c.infoTemplate,g=g&&g.getFieldInfo&&g.getFieldInfo(a),b=l.isFunction(a)?null:c.getField(a),e=g||b,
d="";e&&(d=g&&g.label||b&&b.alias||e.name||e.fieldName);return d},_getRampTitle:function(a,c){var g,b=a.field,e=a.normalizationField,d=!1,z=!1,h=!1,f,b=l.isFunction(b)?null:b,e=l.isFunction(e)?null:e;if(a.legendOptions&&a.legendOptions.title)g=a.legendOptions.title;else{if(c.renderer.authoringInfo&&c.renderer.authoringInfo.visualVariables){var u=c.renderer.authoringInfo.visualVariables;for(f=0;f<u.length;f++){var m=u[f];if("colorInfo"===m.type&&"ratio"===m.style){d=!0;break}else if("colorInfo"===
m.type&&"percent"===m.style){z=!0;break}else if("colorInfo"===m.type&&"percentTotal"===m.style){h=!0;break}}}(d=h&&"showRatioPercentTotal"||z&&"showRatioPercent"||d&&"showRatio"||e&&"showNormField"||b&&"showField"||null)&&(g=H.substitute({field:b&&this._getFieldAlias(b,c),normField:e&&this._getFieldAlias(e,c)},this._i18n[d]))}return g},_getRendererTitle:function(a,c){var g;if(a){var b,e,d;a instanceof J&&(b=a.attributeField,e=a.normalizationField,d="percent-of-total"===a.normalizationType);b=l.isFunction(b)?
null:b;e=l.isFunction(e)?null:e;a.legendOptions&&a.legendOptions.title?g=a.legendOptions.title:(d=e&&"showNormField"||(d?"showNormPct":null)||b&&"showField"||null)&&(g=H.substitute({field:b&&this._getFieldAlias(b,c),normField:e&&this._getFieldAlias(e,c)},this._i18n[d]))}return g},_buildLegendItems_Renderer:function(a,c,g){var t=c.parentLayerId,e=this.map,s=e.getScale(),z,h=!1;if(!this._respectCurrentMapScale||this._isLayerInScale(a,c,s)){var f,u,m="esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass?
a.renderer.renderer:a.renderer,k,E,r,p,q;if(m instanceof W&&(m=(m="zoom"===m.rangeType?m.getRendererInfoByZoom(e.getZoom()):m.getRendererInfoByScale(s))&&m.renderer,!m))return!1;var D=this._getVariables(m),w=d.filter(D,function(a){return!!a}).length,s=D[0],e=D[1],D=D[2],x,A;s&&(k=this._getMedianColor(m,s),s.field&&(r=l.isFunction(s.field)?null:a.getField(s.field)));e&&e.field&&(q=l.isFunction(e.field)?null:a.getField(e.field));D&&D.field&&(p=l.isFunction(D.field)?null:a.getField(D.field));if(m instanceof
Z)z=h=!0,this._showHeatRamp(a,c,m,g);else if(m instanceof X)z=h=!0,this._showDotDensityLegend(a,c,m,g);else if(m instanceof Y)z=h=!0,u=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),f=b.create("tbody",{},u),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(u,a,c),m.latestObservationRenderer&&m.latestObservationRenderer instanceof I&&this._buildRow_Renderer(a,m.latestObservationRenderer.symbol,k,y.encode(m.latestObservationRenderer.label)||this.NLS_currentObservations,
null,f),m.observationRenderer&&m.observationRenderer instanceof I&&this._buildRow_Renderer(a,m.observationRenderer.symbol,k,y.encode(m.observationRenderer.label)||this.NLS_previousObservations,null,f);else if(m instanceof M){if(m.infos&&0<m.infos.length){z=h=!0;u=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);f=b.create("tbody",{},u);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(u,a,c);m.attributeField&&D&&this._addSubHeader(f,this._getFieldAlias(m.attributeField,
a));var B=[];d.forEach(m.infos,function(c){var g=null;a._editable&&a.types&&(g=this._getTemplateFromTypes(a.types,c.value));var b=c.label;null==b&&(b=c.value);-1===d.indexOf(B,b)&&(B.push(b),this._buildRow_Renderer(a,c.symbol,k,y.encode(b),g,f))},this)}A=this._displayDefaultSymbol(a,m,g)}else if(m instanceof J){if(m.infos&&0<m.infos.length||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass){z=h=!0;x=this._isUnclassedRenderer(m);!s&&1===m.infos.length&&(E=(E=m.infos[0])&&E.symbol);x||(u=
b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),f=b.create("tbody",{},u),w=this._getRendererTitle(m,a),this._buildRow_Renderer(a,null,k,y.encode(w),null,f));u=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g);f=b.create("tbody",{},u);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(u,a,c);if(!x||!D)w=m.infos.slice(0).reverse(),d.forEach(w,function(c){var g=c.label;null==g&&!x&&(g=c.minValue+" - "+c.maxValue);this._buildRow_Renderer(a,
c.symbol,k,y.encode(g),null,f)},this);if("esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&(a.renderer.style===P.STYLE_SCALAR||a.renderer.style===P.STYLE_SINGLE_ARROW))this._buildRow_Renderer(a,m.defaultSymbol,null,"",null,f),a._hideDefaultSymbol=!0}x||(A=this._displayDefaultSymbol(a,m,g))}else m instanceof I&&(z=h=!0,u=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),f=b.create("tbody",{},u),(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(u,
a,c),E=null,a._editable&&(a.templates&&0<a.templates.length)&&(E=a.templates[0]),u=1<w?null:r||q||p,this._buildRow_Renderer(a,m.symbol,k,y.encode(u?this._getRampTitle(1<w?null:s||e||D,a):m.label),E,f),E=s?null:m.symbol,u&&(r=q=p=null));if(z){if(s&&(s.field||s.valueExpression))this._showGradientRamp(a,c,m,null,g,s,r,null,D?!0:!1);if(D&&(D.field||D.valueExpression))z=s||m instanceof M?!1:!0,this._showSizeLegend(a,c,m,D,k,g,p,null,z);if(e&&(e.field||e.valueExpression))p=E&&!E.url&&E.color?E.color:this.transparencyRampColor,
this._showGradientRamp(a,c,m,p,g,e,q,null,!1)}A||(A=this._displayDefaultSymbol(a,m,g));h=h||A}h&&(n.set(v.byId(this.id+"_"+a.id+"_"+c.id),"display","block"),-1<t&&(n.set(v.byId(this.id+"_"+a.id+"_"+t+"_group"),"display","block"),this._findParentGroup(a.id,t)));return h},_isUnclassedRenderer:function(a,c){var g;if(a instanceof J&&a.infos&&1===a.infos.length){g=a.attributeField;var b=a.normalizationField;g=c?g===c:!!this._getVariables(a,g,b).length}return g},_displayDefaultSymbol:function(a,c,g){var d;
!a._hideDefaultSymbol&&c.defaultSymbol&&(d=!0,g=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},g),g=b.create("tbody",{},g),this._buildRow_Renderer(a,c.defaultSymbol,null,y.encode(c.defaultLabel)||"others",null,g));return d},_showGradientRamp:function(a,c,g,d,e,s,h,f,k){k=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(!k?" esriLegendSubFragment":"")},e);e=b.create("tbody",{},k);(a._hoverLabel||a._hoverLabels||f)&&this._createHoverAction(k,
a,c,f);(h||s.valueExpression)&&this._addSubHeader(e,this._getRampTitle(s,a));c=s.field;var u;c&&(u=l.isFunction(c)?null:a.getField(c));(s=this._getRampStops(g,s,d,u&&"esriFieldTypeDate"===u.type))&&s.length&&this._drawGradientRamp(e,s,!0,a,this._getRampBorderColor(g),!!d)},_getMedianColor:function(a,c){var g,b;c.colors?(g=c.minDataValue,b=c.maxDataValue):c.stops&&(g=c.stops[0].value,b=c.stops[c.stops.length-1].value);return a.getColor(g+(b-g)/2,{colorInfo:c})},_getRampStops:function(a,c,g,b){var e,
s,h,f,l=!1;c.colors||c.opacityValues?(s=c.maxDataValue-c.minDataValue,e=d.map([0,0.25,0.5,0.75,1],function(a){h=c.minDataValue+a*s;return Number(h.toFixed(6))}),this._checkPrecision(0,4,e)):c.stops&&(e=d.map(c.stops,function(a){return a.value}),(l=d.some(c.stops,function(a){return!!a.label}))&&(f=d.map(c.stops,function(a){return a.label})));var k=e[0],m,n;s=e[e.length-1]-k;return d.map(e,function(d,h){g?(m=new B(g.toRgba()),n=a.getOpacity(d,{opacityInfo:c}),null!=n&&(m.a=n)):m=a.getColor(d,{colorInfo:c});
var z="";if(l)z=f[h];else{var z=b?L.formatDate(d,L.timelineDateFormatOptions):F.format(d),r="";0===h?r=this._specialChars.lt+" ":h===e.length-1&&(r=this._specialChars.gt+" ");z=r+z}return{value:d,color:m,offset:1-(d-k)/s,label:z}},this).reverse()},_checkPrecision:function(a,c,g){var b=a+(c-a)/2,e=g[a],d=g[b],h=g[c],f=Math.floor(e),l=Math.floor(d),k=Math.floor(h);f===e&&(k===h&&l!==d&&f!==l&&k!==l)&&(g[b]=l);a+1!==b&&this._checkPrecision(a,b,g);b+1!==c&&this._checkPrecision(b,c,g)},_getRampBorderColor:function(a){var c;
if(a instanceof I)c=a.symbol;else if(a instanceof M||a instanceof J)c=a.infos[0].symbol;return(a=c&&-1===c.type.indexOf("linesymbol")?c.getStroke():null)&&a.color},_drawGradientRamp:function(a,c,g,t,e,s){var f=b.create("tr",{},a),l,k,u,m,r,p=c.length-1,q;m=0;this.alignRight?(a=b.create("td",{align:this._isRightToLeft?"left":"right"},f),l=b.create("td",{align:this._isRightToLeft?"left":"right",width:this.gradientWidth},f)):(l=b.create("td",{width:this.gradientWidth,align:"center"},f),a=b.create("td",
{},f));f=e&&0<e.a&&!(240<=e.r&&240<=e.g&&240<=e.b);k=b.create("div",{"class":f?"":"esriLegendBorderLessColorRamp",style:"position: relative; width:"+this.gradientWidth+"px;"},l);l=b.create("div",{"class":"esriLegendColorRamp"+(s?" esriLegendTransparencyRamp":"")},k);s=n.get(l,"width");f&&(e=9>h("ie")?e.toHex():"rgba("+e.toRgba().join(",")+")",n.set(l,"border",this.colorRampBorder+" "+e));g?(e=this.gradientHeight*p,n.set(l,"height",e+"px")):e=n.get(l,"height");n.set(k,"height",e+"px");f=A.createSurface(l,
s,e);9>h("ie")&&(m=f.getEventSource(),n.set(m,"position","relative"),n.set(m.parentNode,"position","relative"),m=1);try{g&&d.forEach(c,function(a,c){a.offset=c/p}),r=f.createRect({x:-m,y:-m,width:s+m,height:e+m}),r.setFill({type:"linear",x1:0,y1:0,x2:0,y2:e,colors:c}).setStroke(null),f.createRect({width:s,height:e}).setFill(new B([255,255,255,1-t.opacity])).setStroke(null),this._surfaceItems.push(f)}catch(v){f.clear(),f.destroy()}d.forEach(c,function(a,g){if(a.label){q="top:"+100*a.offset+"%;";var e=
"";0===g&&(e+=" esriLegendColorRampTickFirst");g===c.length-1&&(e+=" esriLegendColorRampTickLast");b.create("div",{"class":"esriLegendColorRampTick"+e,innerHTML:"\x26nbsp;",style:q},k)}});u=b.create("div",{"class":"esriLegendColorRampLabels",style:{height:e+this.gradientHeight+"px"}},a);g?d.forEach(c,function(a){b.create("div",{"class":"esriLegendColorRampLabel",innerHTML:y.encode(a.label)||"\x26nbsp;"},u)}):(b.create("div",{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.high},u),b.create("div",
{"class":"esriLegendColorRampLabel",innerHTML:this._i18n.low,style:"top: "+(e+this.gradientHeight-2*this.gradientHeight)+"px;"},u))},_showHeatRamp:function(a,c,g,d,e){var f,h=g.field;f=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},d);d=b.create("tbody",{},f);(a._hoverLabel||a._hoverLabels||e)&&this._createHoverAction(f,a,c,e);(h=h&&a.getField(h))&&this._addSubHeader(d,this._getFieldAlias(h.name,a));c=this._getHeatmapStops(g);c.length&&this._drawGradientRamp(d,
c,!1,a)},_getHeatmapStops:function(a){var c=a.colorStops;a=a.colors;var g,b,e,f;if(c&&c[0])if(g=c.length-1,a=c[0]&&null!=c[0].ratio){if((a=c[g])&&1!==a.ratio)c=c.slice(0),c.push({ratio:1,color:a.color}),g++}else b=c[0].value,e=c[g].value-b,c=d.map(c,function(a){return{color:a.color,ratio:(a.value-b)/e}});else a&&a[0]&&(g=a.length-1,f=1/(a.length-1),c=d.map(a,function(a,c){return{color:a,ratio:c*f}}));c=d.map(c,function(a,c){var b="";0===c?b="Low":c===g&&(b="High");return{color:a.color,label:b,offset:1-
a.ratio}});return c.reverse()},_showDotDensityLegend:function(a,c,g,t){var e=g.legendOptions,f,h,k,n,u,m,r,p=this.dotDensitySwatchSize,q=Math.round(p/2);e&&(h=e.backgroundColor,k=e.outline,n=e.valueUnit,u=e.dotCoverage);u=(u||this.dotCoverage)/100;r=Math.round(p*p/Math.pow(g.dotSize,2)*u);t=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"},t);m=b.create("tbody",{},t);(a._hoverLabel||a._hoverLabels)&&this._createHoverAction(t,a,c);this._addSubHeader(m,H.substitute({value:g.dotValue,
unit:n||""},this.NLS_dotValue));d.forEach(g.fields,function(c){c=l.mixin({},c);c.numPoints=r;f=new $(g._generateImageSrc(p,p,[c],{x:0,y:0},{x:p,y:p},h),k||g.outline,p,p);c=a.getField(c.name)||c;this._buildRow_Renderer(a,f,null,y.encode(this._getFieldAlias(c.name,a)),null,m,{type:"path",path:"M "+-q+","+-q+" L "+q+","+-q+" L "+q+","+q+" L "+-q+","+q+" L "+-q+","+-q+" E"})},this)},_showSizeLegend:function(a,c,g,d,e,f,h,k,n){var u=d.legendOptions,u=u&&u.customValues;e=this._getSizeSymbol(g,e);if(!(d.valueUnit&&
"unknown"!==d.valueUnit||!e||!u&&(null==d.minSize||null==d.maxSize))){n=b.create("table",{cellpadding:0,cellspacing:0,width:"95%","class":"esriLegendLayer"+(!n?" esriLegendSubFragment":"")},f);f=b.create("tbody",{},n);(a._hoverLabel||a._hoverLabels||k)&&this._createHoverAction(n,a,c,k);(h||d.valueExpression)&&this._addSubHeader(f,this._getRampTitle(d,a));c=d.field;var m;c&&(m=l.isFunction(c)?null:a.getField(c));m=m&&"esriFieldTypeDate"===m.type;u=u||this._getDataValues(g,e,d,m);for(c=n=u.length-1;0<=
c;c--)h=u[c],e=N.fromJson(e.toJson()),this._applySize(e,g,d,h),h=m?L.formatDate(h,L.timelineDateFormatOptions):F.format(h),k="",c===n?k=this._specialChars.gt+" ":0===c&&(k=this._specialChars.lt+" "),k="\x3cspan class\x3d'esriLegendSizeRampLabel'\x3e"+y.encode(k+h)+"\x3c/span\x3e",this._buildRow_Renderer(a,e,null,k,null,f)}},_getSizeSymbol:function(a,c){var b,d;if(a instanceof I)b=a.symbol;else if(a instanceof P)b=a.defaultSymbol;else if(a instanceof M||a instanceof J)b=a.infos[0].symbol,d=1<a.infos.length;
if(b=b&&-1!==b.type.indexOf("fillsymbol")?null:b)if(b=N.fromJson(b.toJson()),c||d)-1!==b.type.indexOf("linesymbol")?b.setColor(new B(this.sizeRampDarkColor)):(b.setColor(new B(this.sizeRampLightColor)),b.setOutline&&(d=new aa,d.setColor(new B(this.sizeRampDarkColor)),d.setWidth(1.5),b.setOutline(d)));return b},_getDataValues:function(a,c,b,f,e,h){e=null==e?5:e;h=null==h?20:h;var l=a.getSizeRangeAtScale(b,this.map.getScale());e=this._interpolateSizeRange(l,e);var k=d.map(e,function(a){return this._getDataValueFromSize(a,
b,l)},this);if(!f){var n,k=F.round(k);for(f=1;f<k.length-1;f++)if(n=this._roundDataValue(a,c,b,k[f],k[f-1],h))k[f]=n[0],e[f]=n[1]}return k},_interpolateSizeRange:function(a,c){var b=a.minSize,d=(a.maxSize-b)/(c-1),e,f=[];for(e=0;e<c;e++)f.push(b+d*e);return f},_getDataValueFromSize:function(a,c,b){var d=b.minSize;b=b.maxSize;var e=c.minDataValue;c=c.maxDataValue;return a=a<=d?e:a>=b?c:(a-d)/(b-d)*(c-e)+e},_roundDataValue:function(a,c,b,d,e,f){var h=this._getSize(c,a,b,d);e=this._getSize(c,a,b,e);
var l,k=F.getDigits(d),n=k.integer,k=k.fractional,m,p,r,q,v,w,x,A,y,B,C;0<d&&1>d&&(l=Math.pow(10,k),d*=l,n=F.getDigits(d).integer);for(n-=1;0<=n&&!(m=Math.pow(10,n),k=Math.floor(d/m)*m,m*=Math.ceil(d/m),null!=l&&(k/=l,m/=l),p=(k+m)/2,p=F.round([k,p,m],{indexes:[1]})[1],r=this._getSize(c,a,b,k),q=this._getSize(c,a,b,m),v=this._getSize(c,a,b,p),w=F.getPctChange(h,r,e,null),x=F.getPctChange(h,q,e,null),A=F.getPctChange(h,v,e,null),y=w.prev<=f,B=x.prev<=f,y&&B&&(w.prev<=x.prev?(y=!0,B=!1):(B=!0,y=!1)),
y?C=[k,r]:B?C=[m,q]:A.prev<=f&&(C=[p,v]),C);n--);return C},_applySize:function(a,c,b,d){var e=a.type;c=this._getSize(a,c,b,d);switch(e){case "simplemarkersymbol":a.setSize(c);break;case "picturemarkersymbol":e=a.width;b=a.height;a.setHeight(c);a.setWidth(c*(e/b));break;case "simplelinesymbol":case "cartographiclinesymbol":a.setWidth(c);break;case "textsymbol":a.font&&a.font.setSize(c)}},_getSize:function(a,c,b,d){return c.getSize(d,{sizeInfo:b,scale:this.map.getScale(),shape:-1!==a.type.indexOf("markersymbol")?
a.style:null})},_buildRow_Renderer:function(a,c,g,d,e,f,h){var k=b.create("tr",{},f),l;this.alignRight?(f=b.create("td",{align:this._isRightToLeft?"left":"right"},k),c&&(l=b.create("td",{align:this._isRightToLeft?"left":"right",width:35},k))):(c&&(l=b.create("td",{width:35,align:"center"},k)),f=b.create("td",{},k));var n=k=30,m;if(c){if("simplemarkersymbol"==c.type)k=Math.min(Math.max(k,c.size+12),125),n=Math.min(Math.max(n,c.size+12),125);else if("picturemarkersymbol"==c.type)k=Math.min(Math.max(k,
c.width),125),n=Math.min(c.height||n,125);else if("textsymbol"==c.type){var p,r;c.text||(p=c.text,r=!0,c.setText(this.defaultText));k=Math.min(Math.max(k,c.getWidth()+12),125);n=Math.min(Math.max(n,c.getHeight()+12),125);r&&c.setText(p)}m=b.create("div",{style:"width:"+k+"px;height:"+n+"px;"},l)}H.isDefined(d)&&"number"===typeof d&&(d=""+d);b.create("td",{innerHTML:d||"",align:this._align},b.create("tr",{},b.create("tbody",{},b.create("table",{width:"95%"},f))));c&&(a=this._drawSymbol(m,c,g,k,n,e,
a,h),this._surfaceItems.push(a))},_addSubHeader:function(a,c){var g=b.create("tr",{},a),g=b.create("td",{align:this._align,colspan:2},g);b.create("td",{innerHTML:y.encode(c)||"",align:this._align},b.create("tr",{},b.create("tbody",{},b.create("table",{width:"95%"},g))))},_drawSymbol:function(a,c,b,d,e,f,k,p){c=N.fromJson(c.toJson());var q=k.opacity;b&&c.setColor(new B(b.toRgba()));if("simplelinesymbol"===c.type||"cartographiclinesymbol"===c.type||"textsymbol"===c.type){if(!c.color)return;b=c.color.toRgba();
b[3]*=q;c.color.setColor(b)}else"simplemarkersymbol"===c.type||"simplefillsymbol"===c.type?(c.color&&(b=c.color.toRgba(),b[3]*=q,c.color.setColor(b)),c.outline&&c.outline.color&&(b=c.outline.color.toRgba(),b[3]*=q,c.outline.color.setColor(b))):"picturemarkersymbol"===c.type&&(a.style.opacity=q,a.style.filter="alpha(opacity\x3d("+100*q+"))");a=A.createSurface(a,d,e);9>h("ie")&&(b=a.getEventSource(),n.set(b,"position","relative"),n.set(b.parentNode,"position","relative"));f=this._getDrawingToolShape(c,
f)||N.getShapeDescriptors(c);var u,q=(b=f.defaultShape)&&"text"===b.type;try{q&&!b.text&&(b.text=this.defaultText),u=a.createShape(p||b).setFill(f.fill).setStroke(f.stroke),q&&u.setFont(f.font)}catch(m){a.clear();a.destroy();return}var v=u.getBoundingBox();p=v.width;f=v.height;var q=-(v.x+p/2),w=-(v.y+f/2);b=a.getDimensions();q={dx:q+b.width/2,dy:w+b.height/2};if("simplemarkersymbol"===c.type&&"path"===c.style)d=k._getScaleMatrix(v,c.size),u.applyTransform(r.scaleAt(d.xx,d.yy,{x:b.width/2,y:b.height/
2}));else if(p>d||f>e)k=p/d>f/e,d=((k?d:e)-5)/(k?p:f),l.mixin(q,{xx:d,yy:d});u.applyTransform(q);return a},_getDrawingToolShape:function(a,c){var b;switch(c?c.drawingTool||null:null){case "esriFeatureEditToolArrow":b={type:"path",path:"M 10,1 L 3,8 L 3,5 L -15,5 L -15,-2 L 3,-2 L 3,-5 L 10,1 Z"};break;case "esriFeatureEditToolTriangle":b={type:"path",path:"M -10,14 L 2,-10 L 14,14 L -10,14 Z"};break;case "esriFeatureEditToolRectangle":b={type:"path",path:"M -10,-10 L 10,-10 L 10,10 L -10,10 L -10,-10 Z"};
break;case "esriFeatureEditToolCircle":b={type:"circle",cx:0,cy:0,r:10};break;case "esriFeatureEditToolEllipse":b={type:"ellipse",cx:0,cy:0,rx:10,ry:5};break;default:return null}return{defaultShape:b,fill:a.getFill(),stroke:a.getStroke()}},_repaintItems:function(){d.forEach(this._surfaceItems,function(a){this._repaint(a)},this)},_repaint:function(a){if(a){a.getStroke&&a.setStroke&&a.setStroke(a.getStroke());try{a.getFill&&a.setFill&&a.setFill(a.getFill())}catch(c){}a.children&&l.isArray(a.children)&&
d.forEach(a.children,this._repaint,this)}},_createHoverAction:function(a,c,d,f){if(f=c._hoverLabel||c._hoverLabels&&c._hoverLabels[d.id]||f)f=y.encode(f),c.mouseMoveHandler=c.mouseMoveHandler||{},c.mouseMoveHandler[d.id]=k.connect(a,"onmousemove",l.hitch(this,function(a,c){this.mouseX=c.clientX;this.mouseY=c.clientY;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,n.set(v.byId(this.id+"_hoverLabel"),"display","none"));setTimeout(l.hitch(this,function(a,c,d){if(a==this.mouseX&&c==this.mouseY&&!this.hoverLabelShowing)if(this.hoverLabelShowing=
!0,v.byId(this.id+"_hoverLabel")){var e=v.byId(this.id+"_hoverLabel");e.innerHTML="\x3cspan\x3e"+d+"\x3c/span\x3e";n.set(e,"top",c+"px");n.set(e,"left",a+15+"px");n.set(e,"display","")}else b.create("div",{innerHTML:"\x3cspan\x3e"+d+"\x3c/span\x3e",id:this.id+"_hoverLabel","class":"esriLegendHoverLabel",style:{top:c+"px",left:a+15+"px"}},document.body)},c.clientX,c.clientY,a),500)},f)),c.mouseOutHandler=c.mouseOutHandler||{},c.mouseOutHandler[d.id]=k.connect(a,"onmouseout",l.hitch(this,function(a){this.mouseY=
this.mouseX=-1;this.hoverLabelShowing&&(this.hoverLabelShowing=!1,n.set(v.byId(this.id+"_hoverLabel"),"display","none"))}))},_removeHoverHandlers:function(){var a;d.forEach(this.layers,function(c){if(c.mouseMoveHandler)for(a in c.mouseMoveHandler)k.disconnect(c.mouseMoveHandler[a]);if(c.mouseOutHandler)for(a in c.mouseOutHandler)k.disconnect(c.mouseOutHandler[a])})},_createDynamicLayers:function(a){var c=[],b;d.forEach(a.dynamicLayerInfos||a.layerInfos,function(d){b={id:d.id};b.source=d.source&&d.source.toJson();
var e;a.layerDefinitions&&a.layerDefinitions[d.id]&&(e=a.layerDefinitions[d.id]);e&&(b.definitionExpression=e);var f;a.layerDrawingOptions&&a.layerDrawingOptions[d.id]&&(f=a.layerDrawingOptions[d.id]);f&&(b.drawingInfo=f.toJson());b.minScale=d.minScale||0;b.maxScale=d.maxScale||0;c.push(b)});return c},_getTemplateFromTypes:function(a,c){var b;for(b=0;b<a.length;b++)if(a[b].id==c&&a[b].templates&&0<a[b].templates.length)return a[b].templates[0];return null},_findParentGroup:function(a,b,d){var f,e=
b.dynamicLayerInfos||b.layerInfos;for(f=0;f<e.length;f++)if(d==e[f].id){-1<e[f].parentLayerId&&(n.set(v.byId(this.id+"_"+a+"_"+e[f].parentLayerId+"_group"),"display","block"),this._findParentGroup(a,b,e[f].parentLayerId));break}},_addSubLayersToHide:function(a){function b(g,f){var e=a.layer.dynamicLayerInfos||a.layer.layerInfos,h,k;for(h=0;h<e.length;h++)if(e[h].id===g&&e[h].subLayerIds)for(k=0;k<e[h].subLayerIds.length;k++){var l=e[h].subLayerIds[k];-1===d.indexOf(f,l)&&(f.push(l),b(l,f))}}a.layer.layerInfos&&
d.forEach(this.hideLayersInLegend[a.layer.id],function(d){b(d,this.hideLayersInLegend[a.layer.id])},this)},_isLayerInScale:function(a,b,d){var f,e=!0;if(a.legendResponse&&a.legendResponse.layers)for(f=0;f<a.legendResponse.layers.length;f++){var h=a.legendResponse.layers[f];if(b.id==h.layerId){var k,l;!a.minScale&&0!==a.minScale||!a.maxScale&&0!==a.maxScale?(0==h.minScale&&a.tileInfo&&(k=a.tileInfo.lods[0].scale),0==h.maxScale&&a.tileInfo&&(l=a.tileInfo.lods[a.tileInfo.lods.length-1].scale)):(k=Math.min(a.minScale,
h.minScale)||a.minScale||h.minScale,l=Math.max(a.maxScale,h.maxScale));if(0<k&&k<d||l>d)e=!1;break}}else if(a.minScale||a.maxScale)if(a.minScale&&a.minScale<d||a.maxScale&&a.maxScale>d)e=!1;return e},_getServiceTitle:function(a){var b=a._titleForLegend;b||((b=a.url)?-1<a.url.indexOf("/MapServer")?(b=a.url.substring(0,a.url.indexOf("/MapServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):-1<a.url.indexOf("/ImageServer")?(b=a.url.substring(0,a.url.indexOf("/ImageServer")),b=b.substring(b.lastIndexOf("/")+
1,b.length)):-1<a.url.indexOf("/FeatureServer")&&(b=a.url.substring(0,a.url.indexOf("/FeatureServer")),b=b.substring(b.lastIndexOf("/")+1,b.length)):b="",a.name&&(b=0<b.length?b+(" - "+a.name):a.name));"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass&&a.vectorFieldPixelFilter&&(a=a.vectorFieldPixelFilter.outputUnit?this["NLS_"+a.vectorFieldPixelFilter.outputUnit]:this["NLS_"+a.vectorFieldPixelFilter.inputUnit],H.isDefined(a)&&(b+=" ("+a+")"));return y.encode(b)},_getEffectiveScale:function(a,
b){var d=b.minScale,f=b.maxScale;if(H.isDefined(b.parentLayerId)){var e=a.layerInfos,h=b.parentLayerId,k;for(k=e.length-1;0<=k;k--)if(e[k].id==h)if(0==d&&0<e[k].minScale?d=e[k].minScale:0<d&&0==e[k].minScale||0<d&&0<e[k].minScale&&(d=Math.min(d,e[k].minScale)),f=Math.max(f||0,e[k].maxScale||0),-1<e[k].parentLayerId)h=e[k].parentLayerId;else break}return{minScale:d,maxScale:f}},_isSupportedLayerType:function(a){return a&&("esri.layers.ArcGISDynamicMapServiceLayer"===a.declaredClass||"esri.layers.ArcGISImageServiceLayer"===
a.declaredClass&&10.2<=a.version||"esri.layers.ArcGISImageServiceVectorLayer"===a.declaredClass||"esri.layers.ArcGISTiledMapServiceLayer"===a.declaredClass||"esri.layers.FeatureLayer"===a.declaredClass||"esri.layers.StreamLayer"===a.declaredClass||"esri.layers.KMLLayer"===a.declaredClass||"esri.layers.GeoRSSLayer"===a.declaredClass||"esri.layers.WMSLayer"===a.declaredClass||"esri.layers.WFSLayer"===a.declaredClass||"esri.layers.CSVLayer"===a.declaredClass)?!0:!1}});l.mixin(G,{ALIGN_LEFT:0,ALIGN_RIGHT:1});
h("extend-esri")&&l.setObject("dijit.Legend",G,O);return G});