// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.18/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/ImageServiceLayerMixin":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/json dojo/_base/config dojo/_base/connect dojo/has dojo/io-query ../kernel ../config ../lang ../request ../deferredUtils ../urlUtils ../geometry/Extent ../geometry/Point ../geometry/Polygon ./MosaicRule ./RasterFunction ./DimensionalDefinition ./Raster ./PixelBlock ./pixelFilters/VectorFieldPixelFilter ./rasterFormats/ImageCanvasDecoder ./TimeInfo ./Field ../graphic ../tasks/ImageServiceIdentifyTask ../tasks/ImageServiceIdentifyParameters".split(" "),
function(m,h,g,n,e,d,c,a,f,k,u,w,z,B,l,t,p,E,v,y,F,D,A,r,I,q,s,x,G,H){m=m(null,{declaredClass:"esri.layers.ImageServiceLayerMixin",_rasterFieldPrefix:"Raster.",_renderingRuleFieldSubPrefix:"ServicePixelValue.",_eventMap:{"rendering-change":!0,"mosaic-rule-change":!0,"spatial-reference-change":!0},constructor:function(b,C){this.useMapTime=C&&C.hasOwnProperty("useMapTime")?!!C.useMapTime:!0},_initialize:function(b,C){this._url=l.urlToObject(b);this.raster=new D(b);this.infoTemplate=C&&C.infoTemplate;
var a=C&&C.imageServiceParameters;this.format=a&&a.format;this.compressionTolerance=a&&a.compressionTolerance?a.compressionTolerance:0.01;this.interpolation=a?a.interpolation:null;this.compressionQuality=a?a.compressionQuality:null;this.bandIds=a?a.bandIds:null;this.mosaicRule=a?a.mosaicRule:null;this.renderingRule=a?a.renderingRule:null;this.useMapDimensionValue=C&&C.hasOwnProperty("useMapDimensionValue")?!!C.useMapDimensionValue:!0;this.activeMapDimensions=C&&C.activeMapDimensions;this._params=
h.mixin({},this._url.query,{f:"image",interpolation:this.interpolation,format:this.format,compressionQuality:this.compressionQuality,bandIds:this.bandIds?this.bandIds.join(","):null},a?a.toJson():{});this.pixelFilter=C&&C.pixelFilter;this.originalPixelData=this.pixelData=null;this.hasDataChanged=!0;this._requestDataHandler=h.hitch(this,this._requestDataHandler);this._requestDataErrorHandler=h.hitch(this,this._requestDataErrorHandler);this._rasterReadPromise=null;this._initLayer=h.hitch(this,this._initLayer);
this._queryVisibleRastersHandler=h.hitch(this,this._queryVisibleRastersHandler);this._visibleRasters=[];this._rasterAttributeTableFields=[];this._rasterAttributeTableFeatures=[];this._renderingRuleAttributeTable={};this._useRenderingRuleAttributeTable=!1;this._loadCallback=C&&C.loadCallback;(a=C&&C.resourceInfo)?this._initLayer(a):z({url:this._url.path,content:h.mixin({f:"json"},this._url.query),callbackParamName:"callback",load:this._initLayer,error:this._errorHandler});this.registerConnectEvents()},
disableClientCaching:!1,_initLayer:function(b,a){if(!(null===b||void 0===b)){this._findCredential();(this.credential&&this.credential.ssl||b&&b._ssl)&&this._useSSL();var c=this.minScale,d=this.maxScale;h.mixin(this,b);this.minScale=c;this.maxScale=d;this.initialExtent=this.fullExtent=this.extent=new t(b.extent);this.spatialReference=this.initialExtent.spatialReference;this.pixelSizeX=parseFloat(this.pixelSizeX);this.pixelSizeY=parseFloat(this.pixelSizeY);for(var f=this.minValues,e=this.maxValues,
k=this.meanValues,x=this.stdvValues,g=this.bands=[],c=0,d=this.bandCount;c<d;c++)g[c]={min:f[c],max:e[c],mean:k[c],stddev:x[c]};this.timeInfo=(c=this.timeInfo)&&c.timeExtent?new q(c):null;d=this.fields=[];if(f=b.fields)for(c=0;c<f.length;c++)d.push(new s(f[c]));this.version=b.currentVersion;this.version||(this.version="fields"in b||"objectIdField"in b||"timeInfo"in b?10:9.3);w.isDefined(b.minScale)&&!this._hasMin&&this.setMinScale(b.minScale);w.isDefined(b.maxScale)&&!this._hasMax&&this.setMaxScale(b.maxScale);
c={};b.defaultMosaicMethod?(c.method=b.defaultMosaicMethod,c.operation=b.mosaicOperator,c.sortField=b.sortField,c.sortValue=b.sortValue):c.method=v.METHOD_NONE;this.defaultMosaicRule=new v(c);this.defaultMosaicRule.ascending=!0;this._useRenderingRuleAttributeTable=10<this.version&&"esriImageServiceDataTypeThematic"===this.serviceDataType&&!this.hasRasterAttributeTable;this._setDefaultRenderingRule(!0);this._isScientificData()&&(!this.mosaicRule||this.mosaicRule&&!this.mosaicRule.multidimensionalDefinition)&&
this._setDefaultMultidimensionalDefinition(!0);10<this.version&&this.hasRasterAttributeTable&&this.getRasterAttributeTable().then(h.hitch(this,function(b){b&&(b.features&&0<b.features.length)&&(this._rasterAttributeTableFeatures=h.clone(b.features));b&&(b.fields&&0<b.fields.length)&&(this._rasterAttributeTableFields=h.clone(b.fields))}));this._isVectorData()&&!w.isDefined(this.pixelFilter)&&(this.vectorFieldPixelFilter=new r,this.vectorFieldPixelFilter.isDataUV="esriImageServiceDataTypeVector-UV"===
this.serviceDataType,this.pixelFilter=this.vectorFieldPixelFilter.computeMagnitudeAndDirection,this.getKeyProperties().then(h.hitch(this,this._setFlowRepresentation)));this.loaded=!0;this.onLoad(this);if(c=this._loadCallback)delete this._loadCallback,c(this)}},getKeyProperties:function(){var b=this._url.path+"/keyProperties",a=new g(B._dfdCanceller);10<this.version?(a._pendingDfd=z({url:b,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),a._pendingDfd.then(function(b){a.callback(b)},
function(b){a.errback(b)})):(b=Error("Layer does not have key properties"),b.log=d.isDebug,a.errback(b));return a},getRasterAttributeTable:function(b){var a=this._url.path+"/rasterAttributeTable",c=new g(B._dfdCanceller),q={f:"json"},f=this.hasRasterAttributeTable;b&&b.renderingRule&&(q.renderingRule=e.toJson(b.renderingRule.toJson()),f=!0);10<this.version&&f?(c._pendingDfd=z({url:a,content:q,handleAs:"json",callbackParamName:"callback"}),c._pendingDfd.then(function(b){c.callback(b)},function(b){c.errback(b)})):
(b=Error("Layer does not support raster attribute table"),b.log=d.isDebug,c.errback(b));return c},_getRenderingRuleAttributeTable:function(b){var a=new g(B._dfdCanceller);if(!b||!b.renderingRule)return a.errback(Error("Rendering rule is not specified")),a;b=b.renderingRule;var c=b.functionName;this._renderingRuleAttributeTable&&c&&this._renderingRuleAttributeTable.hasOwnProperty(c)?a.resolve(this._renderingRuleAttributeTable[c]):a=this.getRasterAttributeTable({renderingRule:b}).then(h.hitch(this,
function(b){var a;b&&(b.features&&b.features.length&&b.fields&&b.fields.length)&&(a={features:h.clone(b.features),fields:h.clone(b.fields)},c&&(this._renderingRuleAttributeTable[c]=a));return a}));return a},_getRasterAttributeTableFeatures:function(){var b=new g;if(this._rasterAttributeTableFeatures&&0<this._rasterAttributeTableFeatures.length)return b.resolve(this._rasterAttributeTableFeatures),b;if(10<this.version&&this.hasRasterAttributeTable)return b=this.getRasterAttributeTable(),b.then(h.hitch(this,
function(b){b&&(b.features&&0<b.features.length)&&(this._rasterAttributeTableFeatures=h.clone(b.features))})),b;b.resolve(this._rasterAttributeTableFeatures);return b},_getRenderingRuleAttributeTableFeatures:function(b){b=b&&b.renderingRule;return!b?(b=new g,b.errback(Error("Rendering rule is not specified")),b):this._getRenderingRuleAttributeTable({renderingRule:b}).then(function(b){return b&&b.features})},getCustomRasterFields:function(b){var a=b?b.rasterAttributeTableFieldPrefix:this._rasterFieldPrefix;
b=10.3<=this.version?"esriFieldTypeDouble":"esriFieldTypeString";var c={name:this._rasterFieldPrefix+"ItemPixelValue",alias:"Item Pixel Value",domain:null,editable:!1,length:50,type:b},d={name:this._rasterFieldPrefix+"ServicePixelValue",alias:"Service Pixel Value",domain:null,editable:!1,length:50,type:b},q={name:this._rasterFieldPrefix+"ServicePixelValue.Raw",alias:"Raw Service Pixel Value",domain:null,editable:!1,length:50,type:"esriFieldTypeDouble"},f=this.fields?h.clone(this.fields):[];b=f.length;
f[b]=d;if(10.4<=this.version&&"esri.layers.ArcGISImageServiceLayer"===this.declaredClass&&(!this.rasterFunctionInfos||!this.rasterFunctionInfos.length||this._isRasterFunctionInfoAvailable("none")))b++,f[b]=q;if(this.capabilities&&-1<this.capabilities.toLowerCase().indexOf("catalog")||this.fields&&0<this.fields.length)b++,f[b]=c;if(w.isDefined(this.pixelFilter)&&("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType))c={name:this._rasterFieldPrefix+
"Magnitude",alias:"Magnitude",domain:null,editable:!1,type:"esriFieldTypeDouble"},d={name:this._rasterFieldPrefix+"Direction",alias:"Direction",domain:null,editable:!1,type:"esriFieldTypeDouble"},b++,f[b]=c,b++,f[b]=d;b=this._rasterAttributeTableFields;if((c=this.renderingRule&&this.renderingRule.functionName)&&this._renderingRuleAttributeTable&&this._renderingRuleAttributeTable.hasOwnProperty(c))b=this._renderingRuleAttributeTable[c].fields;b&&0<b.length&&(b=n.filter(b,function(b){return"esriFieldTypeOID"!==
b.type&&"value"!==b.name.toLowerCase()}),b=n.map(b,function(b){var c=h.clone(b);c.name=a+b.name;return c}),f=f.concat(b));var s=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;10.4<=this.version&&this.rasterFunctionInfos&&n.forEach(this.rasterFunctionInfos,function(b){b&&(b.name&&"none"!==b.name.toLowerCase())&&(b={name:s+b.name.replace(/ /gi,"_"),alias:b.name,domain:null,editable:!1,type:"esriFieldTypeDouble"},f.push(b))});return f},_prepareGetImageParameters:function(b,a,c,d){d=w.isDefined(d)?
d:this._params;var f=b.spatialReference.wkid||e.toJson(b.spatialReference.toJson(!1));delete d._ts;h.mixin(d,{bbox:b.xmin+","+b.ymin+","+b.xmax+","+b.ymax,imageSR:f,bboxSR:f,size:a+","+c},this.disableClientCaching?{_ts:(new Date).getTime()}:{});delete d.compressionTolerance;d.format&&"LERC"===d.format.toUpperCase()&&(d.compressionTolerance=this.compressionTolerance);d.token=this._getToken()},getImageUrl:function(b,a,c,d,q){q=w.isDefined(q)?q:this._params;this._prepareGetImageParameters(b,a,c,q);b=
h.clone(q);this._cleanupRequestParams(b);a=this._url.path+"/exportImage?";c=l.addProxy(a+f.objectToQuery(h.mixin(b,{f:"image"})));var s=b.token;c.length>u.defaults.io.postLength||this.useMapImage?this._jsonRequest=z({url:a,content:h.mixin(b,{f:"json"}),callbackParamName:"callback",load:function(b,a){var c=b.href;s&&(c+=-1===c.indexOf("?")?"?token\x3d"+s:"\x26token\x3d"+s);d(l.addProxy(c))},error:this._errorHandler}):d(c)},onRenderingChange:function(){},onMosaicRuleChange:function(){},setInterpolation:function(b,
a){this.interpolation=this._params.interpolation=b;a||this.refresh(!0)},setCompressionQuality:function(b,a){this.compressionQuality=this._params.compressionQuality=b;a||this.refresh(!0)},setCompressionTolerance:function(b,a){this.compressionTolerance=b;a||this.refresh(!0)},setBandIds:function(b,a){var c=!1;this.bandIds!==b&&(c=!0);this.bandIds=b;this._params.bandIds=b.join(",");if(c&&!a)this.onRenderingChange();a||this.refresh(!0)},setDefaultBandIds:function(b){this.bandIds=this._params.bandIds=null;
b||this.refresh(!0)},setDisableClientCaching:function(b){this.disableClientCaching=b},setMosaicRule:function(b,a){var c=!1;this.mosaicRule!==b&&(c=!0);this.mosaicRule=b;this._params.mosaicRule=e.toJson(b.toJson());if(c&&!a)this.onMosaicRuleChange();a||this.refresh(!0)},setRenderingRule:function(b,a){var c=!1;this.renderingRule!==b&&(c=!0);this.renderingRule=b;this._params.renderingRule=b?e.toJson(b.toJson()):null;this._useRenderingRuleAttributeTable&&this._getRenderingRuleAttributeTable({renderingRule:b});
if(c&&!a)this.onRenderingChange();a||this.refresh(!0)},setImageFormat:function(b,a){this.format=this._params.format=b;a||this.refresh(!0)},setInfoTemplate:function(b){this.infoTemplate=b},setDefinitionExpression:function(b,a){var c=this.mosaicRule?this.mosaicRule.toJson():{};this.mosaicRule||(this.defaultMosaicRule?c=this.defaultMosaicRule.toJson():c.method=v.METHOD_NONE);c.where=b;c=new v(c);this.setMosaicRule(c,a);return this},getDefinitionExpression:function(){return this.mosaicRule?this.mosaicRule.where:
null},setPixelFilter:function(b){this.pixelFilter=b},getPixelData:function(b){return b?(this._useBrowserDecoding()&&(this.originalPixelData={pixelBlock:this._getPixelBlockFromCanvas(this._context,this._map.width,this._map.height),extent:this._map.extent}),this.originalPixelData):this.pixelData},redraw:function(){this.hasDataChanged=!1;this._setPixelData(this.originalPixelData)},queryVisibleRasters:function(b,a,c,d){var q=this._map,f=B._fixDfd(new g(B._dfdCanceller));this._visibleRasters=[];var s,
e,k=!0,x=this.infoTemplate?this.infoTemplate.info:null,u=x?h.clone(this.infoTemplate.info.fieldInfos):null;a=a||{};if(x&&this.infoTemplate.info.mediaInfos&&this.infoTemplate.info.mediaInfos.length){var l=[];n.forEach(this.infoTemplate.info.mediaInfos,function(b){l=l.concat(b&&b.value&&b.value.fields||[])});l.length&&n.forEach(u,function(b){b&&-1<l.indexOf(b.fieldName)&&(b.visible=!0)})}if(u&&0<u.length){k=!1;for(s=0;s<u.length;s++)if((e=u[s])&&e.fieldName.toLowerCase()!==this._rasterFieldPrefix.toLowerCase()+
"servicepixelvalue"&&(e.visible||x.title&&-1<x.title.toLowerCase().indexOf(e.fieldName.toLowerCase()))){k=!0;break}}var w=(e=this._removeVisualizationStretchFunction(this.renderingRule))&&e.functionName,m=[];if(10.4<=this.version){var z=!1;if(this.rasterFunctionInfos&&u){var t=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;n.forEach(this.rasterFunctionInfos,function(b){var a=t+b.name.replace(/ /gi,"_");n.some(u,function(b){return b.visible&&b.fieldName===a})&&(z=z||w&&w===b.name,m.push(new y({rasterFunction:b.name})))})}e&&
!z&&m.push(e)}s=new H;s.geometry=b.geometry;s.returnGeometry=this._map.spatialReference.equals(this.spatialReference);s.returnCatalogItems=k;s.timeExtent=b.timeExtent;s.mosaicRule=this.mosaicRule||null;s.renderingRule=10.4>this.version&&e||null;s.renderingRules=m||null;q&&(b=new p((q.extent.xmax-q.extent.xmin)/(2*q.width),(q.extent.ymax-q.extent.ymin)/(2*q.height),q.extent.spatialReference),s.pixelSize=b);a.requestParams=s;var r=this;b=new G(this.url);(f._pendingDfd=b.execute(s)).addCallbacks(function(b){r._queryVisibleRastersHandler(b,
a,c,d,f)},function(b){r._resolve([b],null,d,f,!0)});return f},_queryVisibleRastersHandler:function(b,a,c,d,q){function f(){var b=this.getCustomRasterFields(a),d=this._getDomainFields(b),e=a?a.returnDomainValues:!1,x=a&&a.rasterAttributeTableFieldPrefix,l,G,H,m,p,r,z,L,v,y;this._useRenderingRuleAttributeTable&&this.renderingRule?(b=this._getRenderingRuleAttributeTableFeatures({renderingRule:this.renderingRule}),y=s):b=this._getRasterAttributeTableFeatures();b.then(h.hitch(this,function(b){for(l=0;l<
g.length;l++){J=g[l];J.setInfoTemplate(this.infoTemplate);J._layer=this;if(s){v=s.replace(/ /gi,"").split(",");G=s;H=v;u&&u.length>=l&&(G=u[l].replace(/ /gi,", "),H=u[l].split(" "));J.attributes[this._rasterFieldPrefix+"ItemPixelValue"]=H;J.attributes[this._rasterFieldPrefix+"ServicePixelValue"]=v;k&&(J.attributes[this._rasterFieldPrefix+"ServicePixelValue.Raw"]=k.replace(/ /gi,"").split(","));if(this.pixelFilter){var a=new A({height:1,width:1,pixelType:"F32",pixels:[],statistics:[]});n.forEach(H,
function(b){a.addData({pixels:[b],statistics:{minValue:b,maxValue:b,noDataValue:null}})});this.pixelFilter({pixelBlock:a,extent:new t(0,0,0,0,this._map.spatialReference)});if("esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType)J.attributes[this._rasterFieldPrefix+"Magnitude"]=a.pixels[0][0],J.attributes[this._rasterFieldPrefix+"Direction"]=a.pixels[1][0]}n.forEach(B,function(b){J.attributes[b.name]=b.value});var f=y||G;if(b&&0<
b.length&&(m=n.filter(b,function(b){if(b&&b.attributes)return b.attributes.hasOwnProperty("Value")?b.attributes.Value==f:b.attributes.VALUE==f}),0<m.length&&(p=h.clone(m[0]),x&&p))){L={};for(r in p.attributes)p.attributes.hasOwnProperty(r)&&(z=x+r,L[z]=p.attributes[r]);p.attributes=L;J.attributes=h.mixin(J.attributes,p.attributes)}}e&&(d&&0<d.length)&&n.forEach(d,function(b){if(b){var a=J.attributes[b.name];w.isDefined(a)&&(a=this._getDomainValue(b.domain,a),w.isDefined(a)&&(J.attributes[b.name]=
a))}},this);R.push(J);this._visibleRasters.push(J)}this._resolve([R,null,!0],null,c,q)}))}var s=b.value,k=b.value,u,g,l=0,G=0,H=this,m=this.objectIdField,p,r,B=[];d=a.requestParams.renderingRules;var v=b.processedValues,y=this.renderingRule&&dojo.toJson(this._removeVisualizationStretchFunction(this.renderingRule).toJson());if(d&&v&&d.length===v.length){var D=this._rasterFieldPrefix+this._renderingRuleFieldSubPrefix;n.forEach(d,function(b,a){if(b.functionName){var c={name:D+b.functionName.replace(/ /gi,
"_"),value:v[a].replace(/ /gi,"").split(",")};B.push(c);y&&y===dojo.toJson(b.toJson())&&(s=v[a])}})}d=this.infoTemplate&&this.infoTemplate.info&&this.infoTemplate.info.layerOptions&&this.infoTemplate.info.layerOptions.hasOwnProperty("showNoDataRecords")?this.infoTemplate.info.layerOptions.showNoDataRecords:!0;if(b.catalogItems){var F=0,I,O,P=b.catalogItems.features.length;r=0;g=Array(P);u=Array(P);p=Array(P);for(l=0;l<P;l++)-1<b.properties.Values[l].toLowerCase().indexOf("nodata")&&r++;I=P-r;for(l=
0;l<P;l++)r=!0,-1<b.properties.Values[l].toLowerCase().indexOf("nodata")?(O=I++,d||(r=!1,g.length--,u.length--,p.length--)):O=F++,r&&(g[O]=b.catalogItems.features[l],u[O]=b.properties.Values[l],p[O]=g[O].attributes[m])}this._visibleRasters=[];var J;if((b=-1<s.toLowerCase().indexOf("nodata"))&&!d)g=[],u=[],p=[];s&&(!g&&!b)&&(m="ObjectId",g=[],J=new x(new t(this.fullExtent),null,{ObjectId:0}),g.push(J));var R=[];g?!this._map.spatialReference.equals(this.spatialReference)&&p&&0<p.length?z({url:this._url.path+
"/query",content:{f:"json",objectIds:p.join(","),returnGeometry:!0,outSR:e.toJson(H._map.spatialReference.toJson()),outFields:m},handleAs:"json",callbackParamName:"callback",load:function(b){if(0===b.features.length)H._resolve([R,null,null],null,c,q);else{for(l=0;l<b.features.length;l++)for(G=0;G<g.length;G++)g[G].attributes[m]==b.features[l].attributes[m]&&(g[G].geometry=new E(b.features[l].geometry),g[G].geometry.setSpatialReference(H._map.spatialReference));f.call(H)}},error:function(b){H._resolve([R,
null,null],null,c,q)}}):f.call(this):this._resolve([R,null,null],null,c,q)},getVisibleRasters:function(){var b=this._visibleRasters,a=[],c;for(c in b)b.hasOwnProperty(c)&&a.push(b[c]);return a},_getDomainFields:function(b){if(b){var a=[];n.forEach(b,function(b){if(b.domain){var c={};c.name=b.name;c.domain=b.domain;a.push(c)}});return a}},_getDomainValue:function(b,a){if(b&&b.codedValues){var c;n.some(b.codedValues,function(b){return b.code===a?(c=b.name,!0):!1});return c}},_requestData:function(b,
a,c){this._rasterReadPromise&&this._rasterReadPromise.cancel();b=h.clone(b);var d=b._normalize(!0);this._prepareGetImageParameters(d,a,c);a=h.clone(this._params);this._cleanupRequestParams(a);a.extent=b;c=null;this._useBrowserDecoding()&&(c=new I({ctx:this._context}));a={imageServiceParameters:a,nBands:Math.min(this.bandCount,3),pixelType:this.pixelType,decodeFunc:c?h.hitch(c,"decode"):null};this._rasterReadPromise=this.raster.read(a,this._requestDataHandler,this._requestDataErrorHandler)},_requestDataHandler:function(b){if(!this._rasterReadPromise||
!this._rasterReadPromise.isCanceled())this.originalPixelData=b,this.hasDataChanged=!0,this._setPixelData(b)},_setPixelData:function(b){b=this._clonePixelData(b);this.pixelFilter&&this.pixelFilter(b);this.pixelData=b;if(!this._rasterReadPromise||!this._rasterReadPromise.isCanceled())this._drawPixelData(),this._rasterReadPromise=null},_clonePixelData:function(b){if(null===b||void 0===b)return b;var a={};b.extent&&(a.extent=h.clone(b.extent));b=b.pixelBlock;if(null===b||void 0===b)return a;a.pixelBlock=
b.clone();return a},_getPixelBlockFromCanvas:function(b,a,c){b=b.getImageData(0,0,a,c).data;for(var d=a*c,q=0,s=0,f=new Uint8Array(d),e=new Uint8Array(d),k=new Uint8Array(d),x=new Uint8Array(d),l=Infinity,g=Infinity,u=Infinity,h=-Infinity,G=-Infinity,H=-Infinity,p,m,w,q=0;q<d;q++)p=b[s++],m=b[s++],w=b[s++],l=l<p?l:p,h=h>p?h:p,g=g<m?g:m,G=G>m?G:m,u=u<w?u:w,H=H>w?H:w,f[q]=p,e[q]=m,k[q]=w,x[q]=b[s++]&1;return new A({width:a,height:c,pixels:[f,e,k],pixelType:"U8",mask:x,statistics:[{minValue:l,maxValue:h},
{minValue:g,maxValue:G},{minValue:u,maxValue:H}]})},_useBrowserDecoding:function(){return(void 0===this.pixelFilter||null===this.pixelFilter)&&("jpeg"===this.format.toLowerCase()||"jpg"===this.format.toLowerCase()||-1<this.format.toLowerCase().indexOf("png"))},getMultidimensionalInfo:function(){var b=this._url.path+"/multiDimensionalInfo",a=new g(B._dfdCanceller);if(this._multidimensionalInfo)return a.resolve(this._multidimensionalInfo),a;10.3<=this.version&&this.hasMultidimensions?(a._pendingDfd=
z({url:b,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}),a._pendingDfd.then(h.hitch(this,function(b){this._multidimensionalInfo=b.multidimensionalInfo;a.callback(b.multidimensionalInfo)}),function(b){a.errback(b)})):(b=Error("Layer does not support multidimensional info"),b.log=d.isDebug,a.errback(b));return a},getDefaultMultidimensionalDefinition:function(){var b,a,c,d=[],q=new g(B._dfdCanceller);if(this._defaultMultidimensionalDefinition)return q.resolve(this._defaultMultidimensionalDefinition),
q;q._pendingDfd=this.getMultidimensionalInfo();q._pendingDfd.then(h.hitch(this,function(s){b=s;a=b.variables[0].dimensions;for(c in a)a.hasOwnProperty(c)&&(a[c].hasRanges&&!0==a[c].hasRanges?d.push(new F({variableName:"",dimensionName:a[c].name,isSlice:!1,values:[a[c].values[0]]})):d.push(new F({variableName:"",dimensionName:a[c].name,isSlice:!0,values:[a[c].extent[0]]})));this._defaultMultidimensionalDefinition=d;q.callback(d)}),function(b){q.errback(b)});return q},_setDefaultMultidimensionalDefinition:function(b){var a,
c={};this.getDefaultMultidimensionalDefinition().then(h.hitch(this,function(d){a=d;0<a.length&&(this.mosaicRule?(c=h.clone(this.mosaicRule),c.multidimensionalDefinition=a):this.defaultMosaicRule?(c=h.clone(this.defaultMosaicRule),c.multidimensionalDefinition=a):c=new v({multidimensionalDefinition:a}),this.setMosaicRule(c,b))}))},_setDefaultRenderingRule:function(b){var a={};if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"!==this.declaredClass&&this.rasterFunctionInfos&&this.rasterFunctionInfos.length&&
"none"!==this.rasterFunctionInfos[0].name.toLowerCase())a.rasterFunction=this.rasterFunctionInfos[0].name;else if(!this.renderingRule&&"esri.layers.ArcGISImageServiceVectorLayer"===this.declaredClass&&10.3<this.version){var c="esriImageServiceDataTypeVector-UV"===this.serviceDataType?7:10;a.rasterFunction="Resample";a.rasterFunctionArguments={ResamplingType:c,InputCellSize:{x:this.pixelSizeX,y:this.pixelSizeY}}}a.hasOwnProperty("rasterFunction")&&(this.defaultRenderingRule=new y(a),this.setRenderingRule(this.defaultRenderingRule,
b))},_cleanupRequestParams:function(b){if(!b)return b;if(b.time&&b.mosaicRule){var a=new v(e.fromJson(b.mosaicRule));if(a&&a.multidimensionalDefinition&&0<a.multidimensionalDefinition.length){var c=n.filter(a.multidimensionalDefinition,function(b){return"StdTime"!==b.dimensionName});a.multidimensionalDefinition=c;b.mosaicRule=e.toJson(a.toJson())}}var a="displayOnPan drawMode styling id opacity visible resourceInfo useMapDimensionValue extent".split(" "),d;for(d in a)b.hasOwnProperty(a[d])&&delete b[a[d]];
return b},_removeVisualizationStretchFunction:function(b){var a=b&&b.functionName;if(!a||"stretch"!==a.toLowerCase())return b;var c=b.functionArguments.Raster;return c&&c.functionName&&n.some(this.rasterFunctionInfos,function(b){return c.functionName===b.name})?c:b},_isScientificData:function(){return"esriImageServiceDataTypeVector-UV"===this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType||"esriImageServiceDataTypeScientific"===this.serviceDataType},_isVectorData:function(){return"esriImageServiceDataTypeVector-UV"===
this.serviceDataType||"esriImageServiceDataTypeVector-MagDir"===this.serviceDataType},_isRasterFunctionInfoAvailable:function(b){return n.some(b&&(this.rasterFunctionInfos||[]),function(a){return a&&a.name&&a.name.toLowerCase()===b.toLowerCase()})},_createPixelData:function(b){b=new A({width:2,height:2,pixels:b,pixelType:this.pixelType,statistics:b});var a=this.fullExtent.getCenter(),a=new t(a.x,a.y,a.x+this.pixelSizeX,a.y+this.pixelSizeY,this.spatialReference);return{pixelBlock:b,extent:a}},_resolve:function(b,
a,c,d,q){a&&this[a].apply(this,b);c&&c.apply(null,b);d&&B._resDfd(d,b,q)},_toggleTime:function(){var b=this._map;this.timeInfo&&this.useMapTime&&b&&!this.suspended?(this._timeConnect||(this._timeConnect=c.connect(b,"onTimeExtentChange",this,this._onTimeExtentChangeHandler)),this._setTime(b.timeExtent)):(c.disconnect(this._timeConnect),this._timeConnect=null,this._setTime(null))},setUseMapTime:function(b,a){this.useMapTime=b;this._toggleTime();!a&&this._map&&this.refresh(!0)},_setTime:function(b){this._params&&
(this._params.time=b?b.toJson().join(","):null)},_onTimeExtentChangeHandler:function(b){this.suspended||(this._setTime(b),this.refresh(!0))},handleSpatialReferenceChange:function(){this.onSpatialReferenceChange()}});a("extend-esri")&&h.setObject("layers.ImageServiceLayerMixin",m,k);return m})},"esri/layers/MosaicRule":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../lang ../geometry/Point".split(" "),function(m,h,g,n,e,d){var c=m(null,{declaredClass:"esri.layers.MosaicRule",
method:null,where:null,sortField:null,sortValue:null,ascending:!1,lockRasterIds:null,viewpoint:null,objectIds:null,operation:null,multidimensionalDefinition:[],constructor:function(a){h.isObject(a)&&(h.mixin(this,a),a.mosaicMethod&&(this.method=a.mosaicMethod),this.method&&"esri"!==this.method.toLowerCase().substring(0,4)&&(this.method=this._getMethodEnum(this.method)),a.mosaicOperation&&(this.operation=a.mosaicOperation),this.operation&&"MT_"!==this.operation.toUpperCase().substring(0,3)&&(this.operation=
this._getOperatorEnum(this.operation)),a.fids&&(this.objectIds=a.fids),a.viewpoint&&(this.viewpoint=new d(a.viewpoint)),this.multidimensionalDefinition=a.multidimensionalDefinition||[])},toJson:function(){var a=null,c=this.multidimensionalDefinition?this.multidimensionalDefinition.length:0;if(c)for(var a=[],d=0;d<c;d++)a.push("esri.layers.DimensionalDefinition"===this.multidimensionalDefinition[d].declaredClass?this.multidimensionalDefinition[d].toJson():this.multidimensionalDefinition[d]);a={mosaicMethod:this.method,
where:this.where,sortField:this.sortField,sortValue:this.sortValue,ascending:this.ascending,lockRasterIds:this.lockRasterIds,viewpoint:this.viewpoint?this.viewpoint.toJson():null,fids:this.objectIds,mosaicOperation:this.operation,multidimensionalDefinition:a};return e.filter(a,function(a){if(null!==a)return!0})},_getMethodEnum:function(a){if(a){var d=c.METHOD_NONE;switch(a.toLowerCase()){case "byattribute":d=c.METHOD_ATTRIBUTE;break;case "center":d=c.METHOD_CENTER;break;case "lockraster":d=c.METHOD_LOCKRASTER;
break;case "nadir":d=c.METHOD_NADIR;break;case "northwest":d=c.METHOD_NORTHWEST;break;case "seamline":d=c.METHOD_SEAMLINE;break;case "viewpoint":d=c.METHOD_VIEWPOINT}return d}},_getOperatorEnum:function(a){if(a)switch(a.toLowerCase()){case "first":return c.OPERATION_FIRST;case "last":return c.OPERATION_LAST;case "max":return c.OPERATION_MAX;case "min":return c.OPERATION_MIN;case "blend":return c.OPERATION_BLEND;case "mean":return c.OPERATION_MEAN;case "sum":return c.OPERATION_SUM}}});h.mixin(c,{METHOD_NONE:"esriMosaicNone",
METHOD_CENTER:"esriMosaicCenter",METHOD_NADIR:"esriMosaicNadir",METHOD_VIEWPOINT:"esriMosaicViewpoint",METHOD_ATTRIBUTE:"esriMosaicAttribute",METHOD_LOCKRASTER:"esriMosaicLockRaster",METHOD_NORTHWEST:"esriMosaicNorthwest",METHOD_SEAMLINE:"esriMosaicSeamline",OPERATION_FIRST:"MT_FIRST",OPERATION_LAST:"MT_LAST",OPERATION_MIN:"MT_MIN",OPERATION_MAX:"MT_MAX",OPERATION_MEAN:"MT_MEAN",OPERATION_BLEND:"MT_BLEND",OPERATION_SUM:"MT_SUM"});g("extend-esri")&&h.setObject("layers.MosaicRule",c,n);return c})},
"esri/layers/RasterFunction":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],function(m,h,g,n,e){var d=m(null,{declaredClass:"esri.layers.RasterFunction",functionName:null,arguments:null,functionArguments:null,variableName:null,outputPixelType:null,constructor:function(c){if(h.isObject(c)){var a=0;this.functionName=c.rasterFunction;this.functionArguments=h.clone(c.rasterFunctionArguments||c.arguments);h.mixin(this,c);if(c=this.functionArguments)if(c.Raster=
this._toRasterFunction(c.Raster),c.Raster2=this._toRasterFunction(c.Raster2),c.DEM=this._toRasterFunction(c.DEM),c.FillRaster=this._toRasterFunction(c.FillRaster),c.Rasters&&c.Rasters.length)for(a=0;a<c.Rasters.length;a++)c.Rasters[a]=this._toRasterFunction(c.Rasters[a])}},_toRasterFunction:function(c){return c&&(c.rasterFunction||c.functionName)?new d(c):c},_rfToJson:function(c){c&&"esri.layers.RasterFunction"===c.declaredClass&&(c=c.toJson());return c},toJson:function(){var c=h.clone(this.functionArguments||
this.arguments);if(c&&(c.Raster=this._rfToJson(c.Raster),c.Raster2=this._rfToJson(c.Raster2),c.DEM=this._rfToJson(c.DEM),c.FillRaster=this._rfToJson(c.FillRaster),c.Rasters&&c.Rasters.length)){var a,d=[];for(a=0;a<c.Rasters.length;a++)d.push(this._rfToJson(c.Rasters[a]));c.Rasters=d}return e.filter({rasterFunction:this.functionName,rasterFunctionArguments:c,variableName:this.variableName,outputPixelType:this.outputPixelType?this.outputPixelType:null},function(a){if(null!==a&&void 0!==a)return!0})}});
g("extend-esri")&&h.setObject("layers.RasterFunction",d,n);return d})},"esri/layers/DimensionalDefinition":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel","../lang"],function(m,h,g,n,e){m=m(null,{declaredClass:"esri.layers.DimensionalDefinition",variableName:null,dimensionName:null,values:[],isSlice:!1,constructor:function(d){h.isObject(d)&&h.mixin(this,d)},toJson:function(){return e.filter({variableName:this.variableName,dimensionName:this.dimensionName,values:this.values,
isSlice:this.isSlice},function(d){return null!==d})}});g("extend-esri")&&h.setObject("layers.DimensionalDefinition",m,n);return m})},"esri/layers/Raster":function(){define("require dojo/_base/declare dojo/_base/lang dojo/_base/Deferred dojo/_base/array dojo/_base/config dojo/json dojo/sniff ../kernel ../Evented ../request ../geometry/Extent ../SpatialReference ../deferredUtils ./PixelBlock ./rasterFormats/LercCodec".split(" "),function(m,h,g,n,e,d,c,a,f,k,u,w,z,B,l,t){var p,E,v,y,F,D;h=h(k,{declaredClass:"esri.layers.Raster",
imageServiceUrl:null,validPixelTypes:"U1 U2 U4 U8 U16 U32 S8 S16 S32 F32".split(" "),validFormats:"lerc jpeg jpg jpgpng png png8 png24 png32 bip bsq tiff".split(" "),_eventMap:{"raster-read-complete":["pixelData","params"]},constructor:function(a){this.imageServiceUrl=a;this.registerConnectEvents();this._loadRasterFormatModules()},read:function(c,d,f){var k=this,l=new n(B._dfdCanceller);if(10>a("ie"))throw"This browser is not supported.";if(!c.imageServiceParameters)throw"Insufficient parameters to read data";
var b=g.clone(c.imageServiceParameters),h=c.pixelType;e.some(this.validPixelTypes,function(b){return b===h})||(b.pixelType="F32");e.some(this.validFormats,function(a){return a.toLowerCase()===b.format.toLowerCase()})||(b.format="lerc");var p=c.decodeFunc,m;this._prepareGetImageParameters(b);l._pendingDfd=u({url:this.imageServiceUrl+"/exportImage",handleAs:"arraybuffer",content:g.mixin(b,{f:"image"}),load:function(a){k.decode(a,{width:b.width,height:b.height,planes:null,pixelType:h,noDataValue:b.noData,
format:b.format,decodeFunc:p}).then(function(a){m={pixelBlock:a,extent:b.extent};k._resolve([m,b],"onRasterReadComplete",d,l)},function(b){k._resolve([b],null,f,l,!0)})},error:function(b){k._resolve([b],null,f,l,!0)}});return l.promise},decode:function(a,c){if(void 0===c||null===c)throw"missing decode options";var d,f;c.format&&(d=c.format.toUpperCase());"BSQ"!==d&&"BIP"!==d&&(d=this._getFormat(a));f=c.decodeFunc;if(void 0===f||null===f)f=this._getFormatDecoderDfd(d);return f(a,c)},onRasterReadComplete:function(){},
_prepareGetImageParameters:function(a){if(a.size&&a.bbox){var d=a.size.split(",");a.width=parseFloat(d[0]);a.height=parseFloat(d[1]);a.extent||(d=a.bbox.split(","),a.extent=new w(parseFloat(d[0]),parseFloat(d[1]),parseFloat(d[2]),parseFloat(d[3]),new z(a.bboxSR)))}else{if(!a.width||Math.floor(a.width)!==a.width||!a.height||Math.floor(a.height)!==a.height)throw"Incorrect Image Dimensions";if(!a.extent||"esri.geometry.Extent"!==a.extent.declaredClass)throw"Incorrect extent";var d=a.extent,f=d.spatialReference.wkid||
c.toJson(d.spatialReference.toJson());delete a._ts;g.mixin(a,{bbox:d.xmin+","+d.ymin+","+d.xmax+","+d.ymax,imageSR:f,bboxSR:f,size:a.width+","+a.height},a.disableClientCaching?{_ts:(new Date).getTime()}:{})}},_adjustExtent:function(a,c,d){var f=a.ymax-a.ymin,e=a.xmax-a.xmin;d>=c?a.ymax=a.ymin+e*c/d:(e=f*d/c,a.xmax=a.xmin+e);return a},_resolve:function(a,c,d,f,e){c&&this[c].apply(this,a);d&&d.apply(null,a);f&&B._resDfd(f,a,e)},_getFormatDecoderDfd:function(a){var c=null;switch(a){case "LERC":c=this._decodeLerc;
break;case "JPEG":c=this._decodeJpeg;break;case "PNG":c=this._decodePng;break;case "BSQ":c=this._decodeBsq;break;case "BIP":c=this._decodeBip;break;case "TIFF":c=this._decodeTiff;break;default:c=function(a,c){throw"The raster format is not supported";}}c=g.hitch(this,c);return function(d,f){var e=new n;try{var b;"LERC"===a||!0===F?(b=c(d,f),e.resolve(b)):D.then(function(){b=c(d,f);e.resolve(b)})}catch(k){e.reject(k)}return e}},_getFormat:function(a){a=new Uint8Array(a,0,10);var c="";if(255===a[0]&&
216===a[1])c="JPEG";else if(137===a[0]&&80===a[1]&&78===a[2]&&71===a[3])c="PNG";else if(67===a[0]&&110===a[1]&&116===a[2]&&90===a[3]&&73===a[4]&&109===a[5]&&97===a[6]&&103===a[7]&&101===a[8]&&32===a[9])c="LERC";else if(-1<String.fromCharCode.apply(null,a).toLowerCase().indexOf("error"))c="ERROR";else if(73===a[0]&&73===a[1]&&42===a[2]&&0===a[3]||77===a[0]&&77===a[1]&&0===a[2]&&42===a[3])c="TIFF";return c},_validateDecodeParams:function(a){if(!a.height||Math.floor(a.height)!==a.height)throw"Height not provided.";
if(!a.width||Math.floor(a.width)!==a.width)throw"Width not provided.";},_decodeJpeg:function(a,c){if(!p)throw"The jpeg decoder module is not loaded.";this._validateDecodeParams(c);var d=(new p).decode(a);if(d.height!==c.height||d.width!==c.width)throw"The decoded image dimensions are incorrect.";var f=[],e,b;for(e=0;e<d.pixels.length;e++)b=d.pixels[e],f.push(this._calculateBandStatistics(b));return new l({width:d.width,height:d.height,pixels:d.pixels,pixelType:"U8",mask:d.mask,statistics:f})},_decodePng:function(a,
c){if(!E)throw"The png decoder module is not loaded.";this._validateDecodeParams(c);var d=new Uint8Array(a),f=new E(d),d=new Uint8Array(4*c.width*c.height);f.copyToImageData(d,f.decodePixels());for(var e=f=0,b,e=new Uint8Array(c.width*c.height),f=0;f<c.width*c.height;f++)e[f]=d[4*f+3];for(var k=new l({width:c.width,height:c.height,pixels:[],pixelType:"U8",mask:e,statistics:[]}),f=0;3>f;f++){b=new Uint8Array(c.width*c.height);for(e=0;e<c.width*c.height;e++)b[e]=d[4*e+f];k.addData({pixels:b,statistics:this._calculateBandStatistics(b)})}return k},
_decodeBsq:function(a,c){if(!v)throw"The bsq decoder module is not loaded.";this._validateDecodeParams(c);r=c.noDataValue;c.pixelType=I(c.pixelType);var d=v.decodeBSQ(a,{bandCount:c.planes,width:c.width,height:c.height,pixelType:A,noDataValue:r}),f=[],e,b=null;for(e=0;e<d.pixels.length;e++)b=d.pixels[e],f.push(this._calculateBandStatistics(b));return new l({width:c.width,height:c.height,pixels:d.pixels,pixelType:c.pixelType,mask:d.maskData,statistics:f})},_decodeBip:function(a,c){this._validateDecodeParams(c);
r=c.noDataValue;c.pixelType=I(c.pixelType);var d=v.decodeBIP(a,{bandCount:c.planes,width:c.width,height:c.height,pixelType:A,noDataValue:r}),f=[],e,b=null;for(e=0;e<d.pixels.length;e++)b=d.pixels[e],f.push(this._calculateBandStatistics(b));return new l({width:c.width,height:c.height,pixels:d.pixels,pixelType:c.pixelType,mask:d.maskData,statistics:f})},_decodeTiff:function(a,c){this._validateDecodeParams(c);r=c.noDataValue;c.pixelType=I(c.pixelType);var d=y.decode(a),f=[],e,b=null;for(e=0;e<d.pixels.length;e++)b=
d.pixels[e],f.push(this._calculateBandStatistics(b,d.maskData));return new l({width:d.width,height:d.height,pixels:d.pixels,pixelType:d.pixelType,mask:d.maskData,statistics:f})},_decodeLerc:function(a,c){this._validateDecodeParams(c);r=c.noDataValue;c.pixelType=I(c.pixelType);for(var d=0,f,e=0,b,k=a.byteLength-10;e<k;){var g=t.decode(a,{inputOffset:e,encodedMaskData:f,returnMask:0===d?!0:!1,returnEncodedMask:0===d?!0:!1,returnFileInfo:!0,pixelType:A,noDataValue:r}),e=g.fileInfo.eofOffset;0===d&&(f=
g.encodedMaskData,b=new l({width:c.width,height:c.height,pixels:[],pixelType:c.pixelType,mask:g.maskData,statistics:[]}));d++;if(g.height!==c.height||g.width!==c.width)throw"The decoded image dimensions are incorrect";b.addData({pixels:g.pixelData,statistics:{minValue:g.minValue,maxValue:g.maxValue,noDataValue:g.noDataValue}})}return b},_calculateBandStatistics:function(a,c){var d=Infinity,f=-Infinity,e=a.length,b,k=0;if(c)for(b=0;b<e;b++)c[b]&&(k=a[b],d=k<d?k:d,f=k>f?k:f);else for(b=0;b<e;b++)k=
a[b],d=k<d?k:d,f=k>f?k:f;return{minValue:d,maxValue:f}},_loadRasterFormatModules:function(){D=new n;10>a("ie")?D.reject("unsupported browser version"):m(["./rasterFormats/JpgPlus","./rasterFormats/Png","./rasterFormats/Raw","./rasterFormats/TiffDecoder","./rasterFormats/Zlib"],function(a,c,d,f){p=a;E=c;v=d;y=f;F=!0;D.resolve(!0)})}});var A=null,r=null,I=function(a){"U1"===a||"U2"===a||"U4"===a||"U8"===a?(a="U8",r=Math.pow(2,8)-1,A=Uint8Array):"U16"===a?(r=r||Math.pow(2,16)-1,A=Uint16Array):"U32"===
a?(r=r||Math.pow(2,32)-1,A=Uint32Array):"S8"===a?(r=r||0-Math.pow(2,7),A=Int8Array):"S16"===a?(r=r||0-Math.pow(2,15),A=Int16Array):"S32"===a?(r=r||0-Math.pow(2,31),A=Int32Array):A=Float32Array;return a};a("extend-esri")&&g.setObject("layers.Raster",h,f);return h})},"esri/layers/PixelBlock":function(){define(["dojo/_base/declare","dojo/_base/lang","dojo/has","../kernel"],function(m,h,g,n){m=m([],{declaredClass:"esri.layers.PixelBlock",planes:null,width:null,height:null,pixelType:null,pixels:[],statistics:[],
constructor:function(e){if(e){if(!e.width||Math.floor(e.width)!==e.width)throw"PixelBlock: incorrect width";if(!e.height||Math.floor(e.height)!==e.height)throw"PixelBlock: incorrect height";if(!e.pixels||!e.statistics)throw"PixelBlock: pixel data or statistics not present";this.width=e.width;this.height=e.height;this.pixels=e.pixels;this.pixelType=e.pixelType||null;this.statistics=e.statistics;this.mask=e.mask||null}},getPlaneCount:function(){return this.pixels.length!==this.statistics.length?console.error("Inconsistent pixel data and statistics"):
this.statistics.length},addData:function(e){if(!e.pixels||!e.statistics)throw"Pixel data or statistics are not present";if(e.pixels.length!==this.width*this.height)throw"Inconsistent pixel data size";this.statistics.push(e.statistics);this.pixels.push(e.pixels)},getAsRGBA:function(){var e=new ArrayBuffer(4*this.width*this.height);switch(this.pixelType){case "S8":case "S16":case "U16":case "S32":case "U32":case "F32":case "F64":this._fillFromNon8Bit(e);break;default:this._fillFrom8Bit(e)}return new Uint8ClampedArray(e)},
getAsRGBAFloat:function(){var e=new Float32Array(4*this.width*this.height);this._fillFrom32Bit(e);return e},clone:function(){var e=new this.constructor;e.width=this.width;e.height=this.height;e.pixelType=this.pixelType;this.mask&&(e.mask=new Uint8Array(this.mask));var d,c;if(this.pixels){e.pixels=[];c=this.pixels.length;for(d=0;d<c;d++)e.pixels[d]=new Float32Array(this.pixels[d])}if(this.statistics){e.statistics=[];c=this.statistics.length;for(d=0;d<c;d++)e.statistics[d]=h.clone(this.statistics[d])}return e},
_fillFrom8Bit:function(e){var d=this.pixels,c=this.mask;if(!e||!d||!d.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");var a,f,k;a=f=k=d[0];3<=d.length&&(f=d[1],k=d[2]);var d=new Uint32Array(e),g=this.width*this.height;if(a.length!==g)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");if(c&&c.length===g)for(e=0;e<g;e++)c[e]&&(d[e]=-16777216|k[e]<<16|f[e]<<8|a[e]);else for(e=0;e<g;e++)d[e]=-16777216|k[e]<<16|f[e]<<8|a[e]},_fillFromNon8Bit:function(e){var d=
this.pixels,c=this.mask,a=this.statistics;if(!e||!d||!d.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");var f=1,k=0;a&&0<a.length?(k=a[0].minValue,f=255/(a[0].maxValue-a[0].minValue)):(f=255,"S8"===this.pixelType?(k=-128,f=127):"U16"===this.pixelType?f=65535:"S16"===this.pixelType?(k=-32768,f=32767):"U32"===this.pixelType?f=4294967295:"S32"===this.pixelType?(k=-2147483648,f=2147483647):"F32"===this.pixelType?(k=-3.4*1E39,f=3.4*1E39):"F64"===this.pixelType&&
(k=-Number.MAX_VALUE,f=Number.MAX_VALUE),f=255/(f-k));e=new Uint32Array(e);var a=this.width*this.height,g,h,m;g=d[0];if(g.length!==a)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");if(3<=d.length)if(h=d[1],m=d[2],c&&c.length===a)for(d=0;d<a;d++)c[d]&&(e[d]=-16777216|(m[d]-k)*f<<16|(h[d]-k)*f<<8|(g[d]-k)*f);else for(d=0;d<a;d++)e[d]=-16777216|(m[d]-k)*f<<16|(h[d]-k)*f<<8|(g[d]-k)*f;else if(c&&c.length===a)for(d=0;d<a;d++)h=(g[d]-k)*f,c[d]&&(e[d]=-16777216|h<<16|h<<8|h);
else for(d=0;d<a;d++)h=(g[d]-k)*f,e[d]=-16777216|h<<16|h<<8|h},_fillFrom32Bit:function(e){var d=this.pixels,c=this.mask;if(!e||!d||!d.length)return console.error("Unable to convert to RGBA. The input pixel block is empty.");var a,f,k;a=f=k=d[0];3<=d.length&&(f=d[1],k=d[2]);var g=this.width*this.height;if(a.length!==g)return console.error("Unable to convert to RGBA. The pixelblock is invalid.");var h=0;if(c&&c.length===g)for(d=0;d<g;d++)e[h++]=a[d],e[h++]=f[d],e[h++]=k[d],e[h++]=c[d];else for(d=0;d<
g;d++)e[h++]=a[d],e[h++]=f[d],e[h++]=k[d],e[h++]=255}});g("extend-esri")&&h.setObject("layers.PixelBlock",m,n);return m})},"esri/layers/rasterFormats/LercCodec":function(){define([],function(){var m={defaultNoDataValue:-3.4027999387901484E38,decode:function(g,n){var e;n=n||{};var d=n.inputOffset||0,c=n.encodedMaskData||null===n.encodedMaskData,a={},f=new Uint8Array(g,d,10);a.fileIdentifierString=String.fromCharCode.apply(null,f);if("CntZImage"!=a.fileIdentifierString.trim())throw"Unexpected file identifier string: "+
a.fileIdentifierString;var d=d+10,k=new DataView(g,d,24);a.fileVersion=k.getInt32(0,!0);a.imageType=k.getInt32(4,!0);a.height=k.getUint32(8,!0);a.width=k.getUint32(12,!0);a.maxZError=k.getFloat64(16,!0);d+=24;if(!c)if(k=new DataView(g,d,16),a.mask={},a.mask.numBlocksY=k.getUint32(0,!0),a.mask.numBlocksX=k.getUint32(4,!0),a.mask.numBytes=k.getUint32(8,!0),a.mask.maxValue=k.getFloat32(12,!0),d+=16,0<a.mask.numBytes){var c=new Uint8Array(Math.ceil(a.width*a.height/8)),k=new DataView(g,d,a.mask.numBytes),
f=k.getInt16(0,!0),u=2,w=0;do{if(0<f)for(;f--;)c[w++]=k.getUint8(u++);else for(var z=k.getUint8(u++),f=-f;f--;)c[w++]=z;f=k.getInt16(u,!0);u+=2}while(u<a.mask.numBytes);if(-32768!==f||w<c.length)throw"Unexpected end of mask RLE encoding";a.mask.bitset=c;d+=a.mask.numBytes}else 0==(a.mask.numBytes|a.mask.numBlocksY|a.mask.maxValue)&&(c=new Uint8Array(Math.ceil(a.width*a.height/8)),a.mask.bitset=c);k=new DataView(g,d,16);a.pixels={};a.pixels.numBlocksY=k.getUint32(0,!0);a.pixels.numBlocksX=k.getUint32(4,
!0);a.pixels.numBytes=k.getUint32(8,!0);a.pixels.maxValue=k.getFloat32(12,!0);d+=16;c=a.pixels.numBlocksX;f=a.pixels.numBlocksY;c+=0<a.width%c?1:0;f+=0<a.height%f?1:0;a.pixels.blocks=Array(c*f);u=1E9;for(z=w=0;z<f;z++)for(var B=0;B<c;B++){var l=0,k=new DataView(g,d,Math.min(10,g.byteLength-d)),t={};a.pixels.blocks[w++]=t;var p=k.getUint8(0);l++;t.encoding=p&63;if(3<t.encoding)throw"Invalid block encoding ("+t.encoding+")";if(2===t.encoding)d++,u=Math.min(u,0);else{if(0!==p&&2!==p){p>>=6;t.offsetType=
p;if(2===p)t.offset=k.getInt8(1),l++;else if(1===p)t.offset=k.getInt16(1,!0),l+=2;else if(0===p)t.offset=k.getFloat32(1,!0),l+=4;else throw"Invalid block offset type";u=Math.min(t.offset,u);if(1===t.encoding)if(p=k.getUint8(l),l++,t.bitsPerPixel=p&63,p>>=6,t.numValidPixelsType=p,2===p)t.numValidPixels=k.getUint8(l),l++;else if(1===p)t.numValidPixels=k.getUint16(l,!0),l+=2;else if(0===p)t.numValidPixels=k.getUint32(l,!0),l+=4;else throw"Invalid valid pixel count type";}d+=l;if(3!=t.encoding)if(0===
t.encoding){k=(a.pixels.numBytes-1)/4;if(k!==Math.floor(k))throw"uncompressed block has invalid length";l=new ArrayBuffer(4*k);p=new Uint8Array(l);p.set(new Uint8Array(g,d,4*k));l=new Float32Array(l);for(p=0;p<l.length;p++)u=Math.min(u,l[p]);t.rawData=l;d+=4*k}else 1===t.encoding&&(k=Math.ceil(t.numValidPixels*t.bitsPerPixel/8),l=Math.ceil(k/4),l=new ArrayBuffer(4*l),p=new Uint8Array(l),p.set(new Uint8Array(g,d,k)),t.stuffedData=new Uint32Array(l),d+=k)}}a.pixels.minValue=u;a.eofOffset=d;var d=null!=
n.noDataValue?n.noDataValue:m.defaultNoDataValue,f=n.encodedMaskData,l=n.returnMask,u=0,w=a.pixels.numBlocksX,z=a.pixels.numBlocksY,B=Math.floor(a.width/w),t=Math.floor(a.height/z),k=2*a.maxZError,f=f||(a.mask?a.mask.bitset:null),E,c=new (n.pixelType||Float32Array)(a.width*a.height);l&&f&&(E=new Uint8Array(a.width*a.height));for(var l=new Float32Array(B*t),v,y,p=0;p<=z;p++){var F=p!==z?t:a.height%z;if(0!==F)for(var D=0;D<=w;D++){var A=D!==w?B:a.width%w;if(0!==A){var r=p*a.width*t+D*B,I=a.width-A,
q=a.pixels.blocks[u],s,x;if(2>q.encoding){if(0===q.encoding)s=q.rawData;else{s=q.stuffedData;x=q.bitsPerPixel;v=q.numValidPixels;y=q.offset;var G=k,H=l,b=a.pixels.maxValue,C=(1<<x)-1,S=0,L=void 0,K=0,N=void 0,Q=void 0,T=Math.ceil((b-y)/G),L=4*s.length-Math.ceil(x*v/8);s[s.length-1]<<=8*L;for(L=0;L<v;L++)0===K&&(Q=s[S++],K=32),K>=x?(N=Q>>>K-x&C,K-=x):(K=x-K,N=(Q&C)<<K&C,Q=s[S++],K=32-K,N+=Q>>>K),H[L]=N<T?y+N*G:b;s=l}x=0}else e=2===q.encoding?0:q.offset;var M;if(f)for(y=0;y<F;y++){r&7&&(M=f[r>>3],M<<=
r&7);for(v=0;v<A;v++)r&7||(M=f[r>>3]),M&128?(E&&(E[r]=1),c[r++]=2>q.encoding?s[x++]:e):(E&&(E[r]=0),c[r++]=d),M<<=1;r+=I}else if(2>q.encoding)for(y=0;y<F;y++){for(v=0;v<A;v++)c[r++]=s[x++];r+=I}else for(y=0;y<F;y++){for(v=0;v<A;v++)c[r++]=e;r+=I}if(1===q.encoding&&x!==q.numValidPixels)throw"Block and Mask do not match";u++}}}e=E;E={width:a.width,height:a.height,pixelData:c,minValue:a.pixels.minValue,maxValue:a.pixels.maxValue,noDataValue:d};e&&(E.maskData=e);n.returnEncodedMask&&a.mask&&(E.encodedMaskData=
a.mask.bitset?a.mask.bitset:null);if(n.returnFileInfo&&(E.fileInfo=h(a),n.computeUsedBitDepths)){e=E.fileInfo;M=a.pixels.numBlocksX*a.pixels.numBlocksY;s={};for(x=0;x<M;x++)d=a.pixels.blocks[x],0===d.encoding?s.float32=!0:1===d.encoding?s[d.bitsPerPixel]=!0:s[0]=!0;a=Object.keys(s);e.bitDepths=a}return E}},h=function(g){return{fileIdentifierString:g.fileIdentifierString,fileVersion:g.fileVersion,imageType:g.imageType,height:g.height,width:g.width,maxZError:g.maxZError,eofOffset:g.eofOffset,mask:g.mask?
{numBlocksX:g.mask.numBlocksX,numBlocksY:g.mask.numBlocksY,numBytes:g.mask.numBytes,maxValue:g.mask.maxValue}:null,pixels:{numBlocksX:g.pixels.numBlocksX,numBlocksY:g.pixels.numBlocksY,numBytes:g.pixels.numBytes,maxValue:g.pixels.maxValue,minValue:g.pixels.minValue,noDataValue:this.noDataValue}}};return m})},"esri/layers/pixelFilters/VectorFieldPixelFilter":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../lang dojo/_base/array".split(" "),function(m,h,g,n,e,d){m=m(null,
{declaredClass:"esri.layers.pixelFilters.VectorFieldPixelFilter",speedUnits:["esriMetersPerSecond","esriKilometersPerHour","esriKnots","esriFeetPerSecond","esriMilesPerHour"],constructor:function(c){h.mixin(this,c);this.isDataUV=c&&c.isDataUV?c.isDataUV:!1;this.computeMagnitudeAndDirection=h.hitch(this,this.computeMagnitudeAndDirection);this.unitConversionFactor=1;this._updateUnitConvFactor()},setUnits:function(c,a){this.inputUnit=c;this.outputUnit=a;this.unitConversionFactor=1;this._updateUnitConvFactor()},
_updateUnitConvFactor:function(){var c=d.indexOf(this.speedUnits,this.inputUnit),a=d.indexOf(this.speedUnits,this.outputUnit);if(this.inputUnit&&this.outputUnit&&0<=c&&0<=a){var f=[1,0.277778,0.514444,0.3048,0.44704,0];this.unitConversionFactor=f[c]/f[a]}},computeMagnitudeAndDirection:function(c){if(!e.isDefined(c))throw"Could not compute magnitude and direction. No pixel data is available.";var a=c.pixelBlock;if(!e.isDefined(a)||2!==a.getPlaneCount())throw"Could not compute magnitude and direction. Pixel data does not contain two bands.";
var d=c.extent,k=(d.xmax-d.xmin)/a.width,g=(d.ymax-d.ymin)/a.height,h=d.xmin+k/2,d=d.ymax-g/2;a.statistics[0].minValue=0;a.statistics[0].maxValue=0;var m=180/Math.PI,n=[],l=0,t=0,p=0,E=!e.isDefined(a.mask),v,y,F,D,A,r,I,q;A=I=Infinity;r=q=-Infinity;for(l=0;l<a.height;l++)for(t=0;t<a.width;t++,p++)if(n.push([h+k*t,d-g*l]),E||a.mask[p])F=v=a.pixels[0][p]*this.unitConversionFactor,D=y=a.pixels[1][p],this.isDataUV&&(F=Math.sqrt(v*v+y*y),D=90-m*Math.atan2(y,v),a.pixels[0][p]=F*this.unitConversionFactor,
a.pixels[1][p]=D),F>r&&(r=F),F<A&&(A=F),D>q&&(q=D),D<I&&(I=D);a.statistics[0].maxValue=r;a.statistics[0].minValue=A;a.statistics[1].maxValue=q;a.statistics[1].minValue=I;c.locations=n;return c}});g("extend-esri")&&h.setObject("layers.pixelFilters.VectorFieldPixelFilter",m,n);return m})},"esri/layers/rasterFormats/ImageCanvasDecoder":function(){define(["require","dojo/_base/declare","dojo/Deferred","dojo/sniff"],function(m,h,g,n){var e;return h(null,{constructor:function(d){this.ctx=d.ctx;this._loadRasterFormatModule()},
decode:function(d,c){if(!c.width||!c.height)throw"Native decoding requires the image format, width and height";var a=new g,f,e=new Uint8Array(d),h=this._getFormat(d);if("error"===h)throw"invalid format";"jpeg"===h&&(f=this._getMask(e,c));var m="",n,B;for(n=0;n<e.length;n+=65535)B=e.subarray(n,n+65535>e.length-1?e.length-1:n+65535),m+=String.fromCharCode.apply(null,B);var e="data:image/"+h+";base64,"+window.btoa(m),l=new Image,t;l.src=e;var p=this;l.onload=function(){p.ctx.clearRect(0,0,c.width,c.height);
p.ctx.drawImage(l,0,0);var d=p.ctx.getImageData(0,0,l.width,l.height);t=d.data;if(f)for(n=0;n<f.length;n++)t[4*n+3]=f[n]?255:0;p.ctx.putImageData(d,0,0);a.resolve(null)};l.onerror=function(){a.reject("cannot load image")};return a},_getFormat:function(d){d=new Uint8Array(d,0,10);var c="error";255===d[0]&&216===d[1]?c="jpeg":137===d[0]&&(80===d[1]&&78===d[2]&&71===d[3])&&(c="png");return c},_getMask:function(d,c){var a;try{if(!e)throw"The zlib decoder module is not loaded.";var f=0,k=0,g=Math.round(d.length/
2);1===g%2&&(g+=1);for(var h=d.length-2,f=g;f<h&&!(255===d[f]&&217===d[f+1]);f++);g=f+=2;if(g<d.length-1){var m=(new e(d.subarray(g))).getBytes();a=new Uint8Array(c.width*c.height);for(f=g=0;f<m.length;f++)for(k=7;0<=k;k--)a[g++]=m[f]>>k&1}}catch(n){}return a},_loadRasterFormatModule:function(){10>n("ie")||m(["./Zlib"],function(d){e=d})}})})},"esri/tasks/ImageServiceIdentifyTask":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../request ../geometry/normalizeUtils ./Task ./ImageServiceIdentifyResult".split(" "),
function(m,h,g,n,e,d,c,a){m=m(c,{declaredClass:"esri.tasks.ImageServiceIdentifyTask",constructor:function(a){this._url.path+="/identify";this._handler=h.hitch(this,this._handler)},__msigns:[{n:"execute",c:3,a:[{i:0,p:["geometry"]}],e:2}],_handler:function(c,d,e,g,h){try{var m=new a(c);this._successHandler([m],"onComplete",e,h)}catch(l){this._errorHandler(l,g,h)}},execute:function(a,c,d,g){var m=g.assembly;a=this._encode(h.mixin({},this._url.query,{f:"json"},a.toJson(m&&m[0])));var n=this._handler,
l=this._errorHandler;return e({url:this._url.path,content:a,callbackParamName:"callback",load:function(a,e){n(a,e,c,d,g.dfd)},error:function(a){l(a,d,g.dfd)}})},onComplete:function(){}});d._createWrappers(m);g("extend-esri")&&h.setObject("tasks.ImageServiceIdentifyTask",m,n);return m})},"esri/tasks/ImageServiceIdentifyResult":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../geometry/jsonUtils ./FeatureSet".split(" "),function(m,h,g,n,e,d){m=m(null,{declaredClass:"esri.tasks.ImageServiceIdentifyResult",
constructor:function(c){c.catalogItems&&(this.catalogItems=new d(c.catalogItems));c.location&&(this.location=e.fromJson(c.location));this.catalogItemVisibilities=c.catalogItemVisibilities;this.name=c.name;this.objectId=c.objectId;this.value=c.value;this.processedValues=c.processedValues;this.properties=c.properties}});g("extend-esri")&&h.setObject("tasks.ImageServiceIdentifyResult",m,n);return m})},"esri/tasks/ImageServiceIdentifyParameters":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/json dojo/_base/array dojo/has ../kernel ../lang ../geometry/jsonUtils".split(" "),
function(m,h,g,n,e,d,c,a){m=m(null,{declaredClass:"esri.tasks.ImageServiceIdentifyParameters",geometry:null,mosaicRule:null,renderingRule:null,renderingRules:null,pixelSizeX:null,pixelSizeY:null,pixelSize:null,returnGeometry:!1,returnCatalogItems:!0,timeExtent:null,toJson:function(d){var e=d&&d.geometry||this.geometry;d={geometry:e,returnGeometry:this.returnGeometry,returnCatalogItems:this.returnCatalogItems,mosaicRule:this.mosaicRule?g.toJson(this.mosaicRule.toJson()):null,renderingRule:this.renderingRule?
g.toJson(this.renderingRule.toJson()):null};e&&(d.geometryType=a.getJsonType(e));e=this.timeExtent;d.time=e?e.toJson().join(","):null;c.isDefined(this.pixelSizeX)&&c.isDefined(this.pixelSizeY)?d.pixelSize=g.toJson({x:parseFloat(this.pixelSizeX),y:parseFloat(this.pixelSizeY)}):this.pixelSize&&(d.pixelSize=this.pixelSize?g.toJson(this.pixelSize.toJson()):null);this.renderingRules&&(d.renderingRules=g.toJson(n.map(this.renderingRules,function(a){return a.toJson()})));return d}});e("extend-esri")&&h.setObject("tasks.ImageServiceIdentifyParameters",
m,d);return m})},"*noref":1}});
define("esri/layers/ArcGISImageServiceLayer","dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../config ./DynamicMapServiceLayer ./ImageServiceLayerMixin".split(" "),function(m,h,g,n,e,d,c){m=m([d,c],{declaredClass:"esri.layers.ArcGISImageServiceLayer",constructor:function(a,c){this._initialize(a,c);this.useMapImage=c&&c.useMapImage||!1},refresh:function(a){if(a)this.inherited(arguments);else{var c=this.disableClientCaching;this.disableClientCaching=!0;this.inherited(arguments);this.disableClientCaching=
c}},exportMapImage:function(a,c){var d=e.defaults.map,d=h.mixin({size:d.width+","+d.height},this._params,a?a.toJson(this.normalization):{},{f:"json"});delete d._ts;this._exportMapImage(this._url.path+"/exportImage",d,c)}});g("extend-esri")&&h.setObject("layers.ArcGISImageServiceLayer",m,n);return m});